### ISSUE TITLE
Bug: ProtonVPN Wireguard port forwarding stop working - unable to grab open port

### ISSUE THREAD

**Issue by CplPwnies** [qdm12/gluetun#1891]
### Is this urgent?

No

### Host OS

Debian Bullseye

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-09-28T14:05:11.407Z (commit d4df872)

### What's the problem 🤔

I just recently switched to ProtonVPN and also gluetun for the NAT-PMP port forwarding support. I have been able to successfully get port forwarding working with the custom wireguard provider, however I've noticed after a period of time, the gluetun container stops being able to get a port from NAT-PMP and the container gets stuck in a restart loop.

The only way I've found to fix this is to generate a new WG config from Proton's website and updating my compose file (essentially switching servers)

### Share your logs (at least 10 lines)

```plain text
2023-10-03T07:48:28-05:00 INFO [ip getter] Public IP address is REDACTED (REDACTED)
2023-10-03T07:48:28-05:00 INFO [vpn] You are running on the bleeding edge of latest!
2023-10-03T07:48:28-05:00 INFO [port forwarding] starting
2023-10-03T07:48:28-05:00 INFO [port forwarding] gateway external IPv4 address is REDACTED
2023-10-03T07:50:36-05:00 ERROR port forwarding loop crashed: starting new service: port forwarding for the first time: adding UDP port mapping: executing remote procedure call: connection timeout: after 2m7.75s
2023-10-03T07:50:36-05:00 ERROR [vpn] port forwarding for the first time: adding UDP port mapping: executing remote procedure call: connection timeout: after 2m7.75s
2023-10-03T07:50:36-05:00 INFO dns ticker: terminated ✔️
2023-10-03T07:50:36-05:00 INFO updater ticker: terminated ✔️
2023-10-03T07:50:36-05:00 INFO http server: terminated ✔️
2023-10-03T07:50:36-05:00 INFO control: terminated ✔️
2023-10-03T07:50:36-05:00 INFO updater: terminated ✔️
2023-10-03T07:50:36-05:00 INFO tickers: terminated ✔️
2023-10-03T07:50:36-05:00 INFO HTTP health server: terminated ✔️
2023-10-03T07:50:37-05:00 WARN vpn: goroutine shutdown timed out: after 1s ⚠️
2023-10-03T07:50:37-05:00 INFO http proxy: terminated ✔️
2023-10-03T07:50:37-05:00 INFO shadowsocks proxy: terminated ✔️
2023-10-03T07:50:37-05:00 INFO unbound: terminated ✔️
2023-10-03T07:50:37-05:00 INFO other: terminated ✔️
2023-10-03T07:50:37-05:00 INFO [routing] routing cleanup...
2023-10-03T07:50:37-05:00 INFO [routing] default route found: interface eth0, gateway REDACTED, assigned IP REDACTED and family v4
2023-10-03T07:50:37-05:00 INFO [routing] deleting route for 0.0.0.0/0
2023-10-03T07:50:37-05:00 INFO [routing] deleting route for REDACTED
2023-10-03T07:50:37-05:00 INFO [routing] deleting route for REDACTED
2023-10-03T07:50:37-05:00 ERROR ordered shutdown timed out: vpn: goroutine shutdown timed out: after 1s
2023-10-03T07:50:37-05:00 INFO Shutdown successful
```

### Share your configuration

```yml
---
version: "3.8"

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=UTC
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - FIREWALL_OUTBOUND_SUBNETS=REDACTED
      - VPN_ENDPOINT_IP=REDACTED
      - VPN_ENDPOINT_PORT=REDACTED
      - WIREGUARD_PUBLIC_KEY=REDACTED
      - WIREGUARD_PRIVATE_KEY=REDACTED
      - WIREGUARD_ADDRESSES=REDACTED
      - VPN_DNS_ADDRESS=REDACTED
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - UPDATER_PERIOD=24h
    volumes:
      - "REDACTED:/gluetun"
    ports:
      - "8888:8888/tcp" # HTP Proxy
      - "8388:8388/tcp" # Shadowsocks
      - "8388:8388/udp" # Shadowsocks
      - "8001:8000/tcp" # HTTP Control Server
      - "8112:8112" # Deluge
    networks:
      - custom_docker_bridge
```

**Comment by Stetsed** [comment]
So I did experience this issue with wireguard aswell and have not been able to figure out why, for now the solution I found is to switch back to OpenVPN and that has worked flawlessly with QBittorrent + A port mapping script to automatically update it.

**Comment by CplPwnies** [comment]
So this is currently happening with my gluetun container again so here is the full log:
```
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version latest built on 2023-10-06T16:15:28.759Z (commit ee413f5)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2023-10-06T15:09:28-05:00 INFO [routing] default route found: interface eth0, gateway REDACTED, assigned IP REDACTED and family v4
2023-10-06T15:09:28-05:00 INFO [routing] local ethernet link found: eth0
2023-10-06T15:09:28-05:00 INFO [routing] local ipnet found: REDACTED
2023-10-06T15:09:28-05:00 INFO [firewall] enabling...
2023-10-06T15:09:28-05:00 INFO [firewall] enabled successfully
2023-10-06T15:09:29-05:00 INFO [storage] merging by most recent 17689 hardcoded servers and 17689 servers read from /gluetun/servers.json
2023-10-06T15:09:29-05:00 INFO Alpine version: 3.18.4
2023-10-06T15:09:29-05:00 INFO OpenVPN 2.5 version: 2.5.8
2023-10-06T15:09:29-05:00 INFO OpenVPN 2.6 version: 2.6.5
2023-10-06T15:09:29-05:00 INFO Unbound version: 1.17.1
2023-10-06T15:09:29-05:00 INFO IPtables version: v1.8.9
2023-10-06T15:09:29-05:00 INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: custom
|   |   ├── Server selection settings:
|   |   |   ├── VPN type: wireguard
|   |   |   ├── Target IP address: REDACTED
|   |   |   └── Wireguard selection settings:
|   |   |       ├── Endpoint IP address: REDACTED
|   |   |       ├── Endpoint port: REDACTED
|   |   |       └── Server public key: REDACTED
|   |   └── Automatic port forwarding settings:
|   |       ├── Use code for provider: protonvpn
|   |       └── Forwarded port file path: /tmp/gluetun/forwarded_port
|   └── Wireguard settings:
|       ├── Private key: REDACTED
|       ├── Interface addresses:
|       |   └── REDACTED
|       ├── Allowed IPs:
|       |   ├── 0.0.0.0/0
|       |   └── ::/0
|       └── Network interface: tun0
|           └── MTU: 1400
├── DNS settings:
|   ├── Keep existing nameserver(s): no
|   ├── DNS server address to use: 127.0.0.1
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Unbound settings:
|       |   ├── Authoritative servers:
|       |   |   └── cloudflare
|       |   ├── Caching: yes
|       |   ├── IPv6: no
|       |   ├── Verbosity level: 1
|       |   ├── Verbosity details level: 0
|       |   ├── Validation log level: 0
|       |   ├── System user: root
|       |   └── Allowed networks:
|       |       ├── 0.0.0.0/0
|       |       └── ::/0
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:127.0.0.1/104
|               ├── ::ffff:10.0.0.0/104
|               ├── ::ffff:169.254.0.0/112
|               ├── ::ffff:172.16.0.0/108
|               └── ::ffff:192.168.0.0/112
├── Firewall settings:
|   ├── Enabled: yes
|   └── Outbound subnets:
|       ├── REDACTED
|       └── REDACTED
├── Log settings:
|   └── Log level: INFO
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   ├── Duration to wait after success: 5s
|   ├── Read header timeout: 100ms
|   ├── Read timeout: 500ms
|   └── VPN wait durations:
|       ├── Initial duration: 6s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   ├── Process GID: 1000
|   └── Timezone: UTC
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   └── IP file path: /tmp/gluetun/ip
└── Version settings:
    └── Enabled: yes
2023-10-06T15:09:29-05:00 INFO [routing] default route found: interface eth0, gateway REDACTED, assigned IP REDACTED and family v4
2023-10-06T15:09:29-05:00 INFO [routing] adding route for 0.0.0.0/0
2023-10-06T15:09:29-05:00 INFO [firewall] setting allowed subnets...
2023-10-06T15:09:29-05:00 INFO [routing] default route found: interface eth0, gateway REDACTED, assigned IP REDACTED and family v4
2023-10-06T15:09:29-05:00 INFO [routing] adding route for REDACTED
2023-10-06T15:09:29-05:00 INFO [routing] adding route for REDACTED
2023-10-06T15:09:29-05:00 INFO [dns] using plaintext DNS at address 1.1.1.1
2023-10-06T15:09:29-05:00 INFO [http server] http server listening on [::]:8000
2023-10-06T15:09:29-05:00 INFO [healthcheck] listening on 127.0.0.1:9999
2023-10-06T15:09:29-05:00 INFO [firewall] allowing VPN connection...
2023-10-06T15:09:29-05:00 INFO [wireguard] Using available kernelspace implementation
2023-10-06T15:09:29-05:00 INFO [wireguard] Connecting to REDACTED:REDACTED
2023-10-06T15:09:29-05:00 INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2023-10-06T15:09:29-05:00 INFO [dns] downloading DNS over TLS cryptographic files
2023-10-06T15:09:37-05:00 INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
2023-10-06T15:09:37-05:00 INFO [vpn] stopping
2023-10-06T15:09:37-05:00 ERROR [vpn] stopping port forwarding: interface not set
2023-10-06T15:09:37-05:00 ERROR [vpn] cannot get version information: Get "https://api.github.com/repos/qdm12/gluetun/commits": context canceled
2023-10-06T15:09:37-05:00 INFO [port forwarding] starting
2023-10-06T15:09:37-05:00 ERROR [ip getter] Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 1.1.1.1:53: write udp REDACTED:REDACTED->1.1.1.1:53: write: operation not permitted - retrying in 5s
2023-10-06T15:09:37-05:00 ERROR port forwarding loop crashed: starting new service: port forwarding for the first time: getting external IPv4 address: executing remote procedure call: writing to connection: write udp 10.50.1.7:42656->10.2.0.1:5351: write: operation not permitted
2023-10-06T15:09:37-05:00 ERROR [vpn] port forwarding for the first time: getting external IPv4 address: executing remote procedure call: writing to connection: write udp REDACTED:REDACTED->REDACTED:REDACTED: write: operation not permitted
2023-10-06T15:09:37-05:00 INFO dns ticker: terminated ✔️
2023-10-06T15:09:37-05:00 INFO updater ticker: terminated ✔️
2023-10-06T15:09:37-05:00 INFO http server: terminated ✔️
2023-10-06T15:09:37-05:00 INFO control: terminated ✔️
2023-10-06T15:09:37-05:00 INFO updater: terminated ✔️
2023-10-06T15:09:37-05:00 INFO tickers: terminated ✔️
2023-10-06T15:09:37-05:00 INFO HTTP health server: terminated ✔️
2023-10-06T15:09:38-05:00 WARN vpn: goroutine shutdown timed out: after 1s ⚠️
2023-10-06T15:09:38-05:00 INFO shadowsocks proxy: terminated ✔️
2023-10-06T15:09:38-05:00 INFO http proxy: terminated ✔️
2023-10-06T15:09:38-05:00 INFO unbound: terminated ✔️
2023-10-06T15:09:38-05:00 INFO other: terminated ✔️
2023-10-06T15:09:38-05:00 INFO [routing] routing cleanup...
2023-10-06T15:09:38-05:00 INFO [routing] default route found: interface eth0, gateway REDACTED, assigned IP REDACTED and family v4
2023-10-06T15:09:38-05:00 INFO [routing] deleting route for 0.0.0.0/0
2023-10-06T15:09:38-05:00 INFO [routing] deleting route for REDACTED
2023-10-06T15:09:38-05:00 INFO [routing] deleting route for REDACTED
2023-10-06T15:09:38-05:00 ERROR ordered shutdown timed out: vpn: goroutine shutdown timed out: after 1s
2023-10-06T15:09:38-05:00 INFO Shutdown successful
```

**Comment by lucantonissen** [comment]
I had just had the exact same issue with protonvpn and it turns out the vpn server I connected to was down. I just switched to another server that was up according to protonvpn, but I got the same result. When I tried again a different server, but this time in another country, the issue was solved somehow.

**Comment by qdm12** [comment]
@CplPwnies the last log you sent has a few interesting things, although it seems unrelated to the original issue. What you see are consequences of the VPN tunnel being unhealthy (connecitivity not working). In more details:

- `stopping port forwarding: interface not set` this was fixed today; more of an informational log than anything impactful at all
- All the `operation not permitted` at the end of an error logged, it's the firewall blocking it, and that's usually because the VPN is not working yet, so the firewall blocks it. Now this is interesting because both the ipinfo.io and port forwarding error in your logs happen AFTER the VPN is stopped, but originates from the first VPN start. A few things get started in a "non-blocking" manner when the tunnel is up (even if it's unhealthy and doesn't work, for Wireguard) in this order: allowing input ports, setting up DNS, get the public ip information, get the version information, and start port forwarding. I will keep it non blocking so the VPN can be stopped/started without having to wait for all these steps to complete (fail or success); Now the problem is the port forwarding error can be logged, but must not be treated as a critical error as it was to let the VPN restart and not exit the program. This is fixed in 1c43a1d55bf38c85651e8a6b74e12026116f1545

**Comment by CplPwnies** [comment]
@qdm12  - Yes, the log I posted yesterday seemed to be a ProtonVPN issue. I switched VPN servers and this fixed that issue.

To answer your other question though about the original error and log - yes, the port forwarding stops working even though it does grab the external IP correctly. It's super strange.

**Comment by CplPwnies** [comment]
Okay, Apologies for the radio silence on this - I thought I might have corrected the issue due to a misconfiguration on one of my containerized applications still seeking out it's own NAT-PMP and causing me to grab more than one port-forward, but I have since fixed that and everything seemed stable... until last night when I lost my port-forward again. Here is the log from the past ~5 days:
```
========================================
========================================
=============== gluetun ================
========================================
=========== Made with ❤️ by ============
======= https://github.com/qdm12 =======
========================================
========================================

Running version latest built on 2023-10-07T13:26:08.155Z (commit 1c43a1d)

🔧 Need help? https://github.com/qdm12/gluetun/discussions/new
🐛 Bug? https://github.com/qdm12/gluetun/issues/new
✨ New feature? https://github.com/qdm12/gluetun/issues/new
☕ Discussion? https://github.com/qdm12/gluetun/discussions/new
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2023-10-18T17:10:52-05:00 INFO [routing] default route found: interface eth0, gateway REDACTED, assigned IP REDACTED and family v4
2023-10-18T17:10:52-05:00 INFO [routing] local ethernet link found: eth0
2023-10-18T17:10:52-05:00 INFO [routing] local ipnet found: REDACTED
2023-10-18T17:10:52-05:00 INFO [firewall] enabling...
2023-10-18T17:10:52-05:00 INFO [firewall] enabled successfully
2023-10-18T17:10:54-05:00 INFO [storage] merging by most recent 17689 hardcoded servers and 17689 servers read from /gluetun/servers.json
2023-10-18T17:10:54-05:00 INFO Alpine version: 3.18.4
2023-10-18T17:10:54-05:00 INFO OpenVPN 2.5 version: 2.5.8
2023-10-18T17:10:54-05:00 INFO OpenVPN 2.6 version: 2.6.5
2023-10-18T17:10:54-05:00 INFO Unbound version: 1.17.1
2023-10-18T17:10:54-05:00 INFO IPtables version: v1.8.9
2023-10-18T17:10:54-05:00 INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: custom
|   |   ├── Server selection settings:
|   |   |   ├── VPN type: wireguard
|   |   |   └── Wireguard selection settings:
|   |   |       ├── Endpoint IP address: REDACTED
|   |   |       ├── Endpoint port: 51820
|   |   |       └── Server public key: REDACTED
|   |   └── Automatic port forwarding settings:
|   |       ├── Use code for provider: protonvpn
|   |       └── Forwarded port file path: /gluetun/forwarded_port
|   └── Wireguard settings:
|       ├── Private key: IOr...GU=
|       ├── Interface addresses:
|       |   └── REDACTED
|       ├── Allowed IPs:
|       |   ├── 0.0.0.0/0
|       |   └── ::/0
|       └── Network interface: tun0
|           └── MTU: 1400
├── DNS settings:
|   ├── Keep existing nameserver(s): no
|   ├── DNS server address to use: 127.0.0.1
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Unbound settings:
|       |   ├── Authoritative servers:
|       |   |   └── cloudflare
|       |   ├── Caching: yes
|       |   ├── IPv6: no
|       |   ├── Verbosity level: 1
|       |   ├── Verbosity details level: 0
|       |   ├── Validation log level: 0
|       |   ├── System user: root
|       |   └── Allowed networks:
|       |       ├── 0.0.0.0/0
|       |       └── ::/0
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:127.0.0.1/104
|               ├── ::ffff:10.0.0.0/104
|               ├── ::ffff:169.254.0.0/112
|               ├── ::ffff:172.16.0.0/108
|               └── ::ffff:192.168.0.0/112
├── Firewall settings:
|   ├── Enabled: yes
|   └── Outbound subnets:
|       ├── REDACTED
|       └── REDACTED
├── Log settings:
|   └── Log level: INFO
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   ├── Duration to wait after success: 5s
|   ├── Read header timeout: 100ms
|   ├── Read timeout: 500ms
|   └── VPN wait durations:
|       ├── Initial duration: 6s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   └── Logging: yes
├── OS Alpine settings:
|   ├── Process UID: 1000
|   ├── Process GID: 1000
|   └── Timezone: america/chicago
├── Public IP settings:
|   ├── Fetching: every 12h0m0s
|   └── IP file path: /tmp/gluetun/ip
└── Version settings:
    └── Enabled: yes
2023-10-18T17:10:54-05:00 INFO [routing] default route found: interface eth0, gateway REDACTED, assigned IP REDACTED and family v4
2023-10-18T17:10:54-05:00 INFO [routing] adding route for 0.0.0.0/0
2023-10-18T17:10:54-05:00 INFO [firewall] setting allowed subnets...
2023-10-18T17:10:54-05:00 INFO [routing] default route found: interface eth0, gateway REDACTED, assigned IP REDACTED and family v4
2023-10-18T17:10:54-05:00 INFO [routing] adding route for REDACTED
2023-10-18T17:10:54-05:00 INFO [routing] adding route for REDACTED
2023-10-18T17:10:54-05:00 INFO [dns] using plaintext DNS at address 1.1.1.1
2023-10-18T17:10:54-05:00 INFO [http server] http server listening on [::]:8000
2023-10-18T17:10:54-05:00 INFO [firewall] allowing VPN connection...
2023-10-18T17:10:54-05:00 INFO [healthcheck] listening on 127.0.0.1:9999
2023-10-18T17:10:54-05:00 INFO [wireguard] Using available kernelspace implementation
2023-10-18T17:10:54-05:00 INFO [wireguard] Connecting to REDACTED:51820
2023-10-18T17:10:54-05:00 INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2023-10-18T17:10:54-05:00 INFO [dns] downloading DNS over TLS cryptographic files
2023-10-18T17:10:56-05:00 INFO [healthcheck] healthy!
2023-10-18T17:10:57-05:00 INFO [dns] downloading hostnames and IP block lists
2023-10-18T17:11:04-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
2023-10-18T17:11:04-05:00 INFO [dns] init module 0: validator
2023-10-18T17:11:04-05:00 INFO [dns] init module 1: iterator
2023-10-18T17:11:04-05:00 INFO [dns] start of service (unbound 1.17.1).
2023-10-18T17:11:05-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-18T17:11:05-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-18T17:11:06-05:00 INFO [dns] ready
2023-10-18T17:11:06-05:00 INFO [healthcheck] healthy!
2023-10-18T17:11:07-05:00 INFO [vpn] You are running on the bleeding edge of latest!
2023-10-18T17:11:07-05:00 INFO [port forwarding] starting
2023-10-18T17:11:07-05:00 INFO [port forwarding] gateway external IPv4 address is REDACTED
2023-10-18T17:11:07-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-18T17:11:07-05:00 INFO [port forwarding] port forwarded is REDACTED
2023-10-18T17:11:07-05:00 INFO [firewall] setting allowed input port REDACTED through interface tun0...
2023-10-18T17:11:07-05:00 INFO [port forwarding] writing port file /gluetun/forwarded_port
2023-10-18T18:16:37-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-18T19:29:47-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-18T20:35:14-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-18T21:59:10-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-18T21:59:10-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-18T23:12:31-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T00:20:02-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T01:32:47-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T02:32:53-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T03:33:09-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T04:33:35-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T05:11:09-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-19T05:33:43-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T06:34:04-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T07:34:12-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T08:34:37-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T08:44:19-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-19T08:44:20-05:00 INFO [healthcheck] healthy!
2023-10-19T08:47:00-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-19T08:47:01-05:00 INFO [healthcheck] healthy!
2023-10-19T09:17:05-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T09:17:07-05:00 INFO [healthcheck] healthy!
2023-10-19T09:17:15-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T09:17:16-05:00 INFO [healthcheck] healthy!
2023-10-19T09:19:57-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T09:19:58-05:00 INFO [healthcheck] healthy!
2023-10-19T09:28:15-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-19T09:28:17-05:00 INFO [healthcheck] healthy!
2023-10-19T09:34:56-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T09:44:02-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-19T09:44:03-05:00 INFO [healthcheck] healthy!
2023-10-19T10:35:20-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T11:35:34-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T12:35:57-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T13:36:18-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T14:09:10-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:09:12-05:00 INFO [healthcheck] healthy!
2023-10-19T14:09:20-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:09:22-05:00 INFO [healthcheck] healthy!
2023-10-19T14:10:01-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:10:06-05:00 INFO [healthcheck] healthy!
2023-10-19T14:10:27-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:10:32-05:00 INFO [healthcheck] healthy!
2023-10-19T14:16:00-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-19T14:16:03-05:00 INFO [healthcheck] healthy!
2023-10-19T14:16:11-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:16:19-05:00 INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
2023-10-19T14:16:19-05:00 INFO [vpn] stopping
2023-10-19T14:16:19-05:00 INFO [port forwarding] stopping
2023-10-19T14:16:19-05:00 INFO [firewall] removing allowed port REDACTED...
2023-10-19T14:16:19-05:00 INFO [port forwarding] removing port file /gluetun/forwarded_port
2023-10-19T14:16:19-05:00 INFO [vpn] starting
2023-10-19T14:16:19-05:00 INFO [firewall] allowing VPN connection...
2023-10-19T14:16:19-05:00 INFO [wireguard] Using available kernelspace implementation
2023-10-19T14:16:19-05:00 INFO [wireguard] Connecting to REDACTED:51820
2023-10-19T14:16:19-05:00 INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2023-10-19T14:16:19-05:00 INFO [port forwarding] starting
2023-10-19T14:16:19-05:00 INFO [port forwarding] gateway external IPv4 address is REDACTED
2023-10-19T14:16:20-05:00 INFO [port forwarding] port forwarded is REDACTED
2023-10-19T14:16:20-05:00 INFO [firewall] setting allowed input port REDACTED through interface tun0...
2023-10-19T14:16:20-05:00 INFO [port forwarding] writing port file /gluetun/forwarded_port
2023-10-19T14:16:21-05:00 INFO [healthcheck] healthy!
2023-10-19T14:16:29-05:00 ERROR [ip getter] Get "https://ipinfo.io/": dial tcp: lookup ipinfo.io on 127.0.0.1:53: read udp 127.0.0.1:46214->127.0.0.1:53: i/o timeout - retrying in 5s
2023-10-19T14:16:34-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-19T14:17:29-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-19T14:17:31-05:00 INFO [healthcheck] healthy!
2023-10-19T14:17:39-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:17:41-05:00 INFO [healthcheck] healthy!
2023-10-19T14:17:49-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:17:51-05:00 INFO [healthcheck] healthy!
2023-10-19T14:18:17-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:18:20-05:00 INFO [healthcheck] healthy!
2023-10-19T14:23:43-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-19T14:23:45-05:00 INFO [healthcheck] healthy!
2023-10-19T14:24:09-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:24:11-05:00 INFO [healthcheck] healthy!
2023-10-19T14:24:25-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:24:27-05:00 INFO [healthcheck] healthy!
2023-10-19T14:25:18-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-19T14:25:20-05:00 INFO [healthcheck] healthy!
2023-10-19T14:25:28-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-19T14:25:30-05:00 INFO [healthcheck] healthy!
2023-10-19T14:25:56-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-19T14:26:04-05:00 INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
2023-10-19T14:26:04-05:00 INFO [vpn] stopping
2023-10-19T14:26:04-05:00 INFO [port forwarding] stopping
2023-10-19T14:26:04-05:00 INFO [firewall] removing allowed port REDACTED...
2023-10-19T14:26:04-05:00 INFO [port forwarding] removing port file /gluetun/forwarded_port
2023-10-19T14:26:04-05:00 INFO [vpn] starting
2023-10-19T14:26:04-05:00 INFO [firewall] allowing VPN connection...
2023-10-19T14:26:04-05:00 INFO [wireguard] Using available kernelspace implementation
2023-10-19T14:26:04-05:00 INFO [wireguard] Connecting to REDACTED:51820
2023-10-19T14:26:04-05:00 INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2023-10-19T14:26:04-05:00 INFO [port forwarding] starting
2023-10-19T14:26:14-05:00 INFO [healthcheck] healthy!
2023-10-19T14:26:14-05:00 INFO [port forwarding] gateway external IPv4 address is REDACTED
2023-10-19T14:26:15-05:00 INFO [port forwarding] port forwarded is REDACTED
2023-10-19T14:26:15-05:00 INFO [firewall] setting allowed input port REDACTED through interface tun0...
2023-10-19T14:26:15-05:00 INFO [port forwarding] writing port file /gluetun/forwarded_port
2023-10-19T14:26:15-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-19T14:26:58-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:27:06-05:00 INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
2023-10-19T14:27:06-05:00 INFO [vpn] stopping
2023-10-19T14:27:06-05:00 INFO [port forwarding] stopping
2023-10-19T14:27:06-05:00 INFO [firewall] removing allowed port REDACTED...
2023-10-19T14:27:06-05:00 INFO [port forwarding] removing port file /gluetun/forwarded_port
2023-10-19T14:27:06-05:00 INFO [vpn] starting
2023-10-19T14:27:06-05:00 INFO [firewall] allowing VPN connection...
2023-10-19T14:27:06-05:00 INFO [wireguard] Using available kernelspace implementation
2023-10-19T14:27:06-05:00 INFO [wireguard] Connecting to REDACTED:51820
2023-10-19T14:27:06-05:00 INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2023-10-19T14:27:06-05:00 INFO [port forwarding] starting
2023-10-19T14:27:17-05:00 INFO [healthcheck] program has been unhealthy for 11s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
2023-10-19T14:27:18-05:00 INFO [vpn] stopping
2023-10-19T14:27:21-05:00 ERROR [ip getter] Get "https://ipinfo.io/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) - retrying in 5s
2023-10-19T14:27:42-05:00 ERROR [ip getter] Get "https://ipinfo.io/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) - retrying in 10s
2023-10-19T14:28:03-05:00 ERROR [ip getter] Get "https://ipinfo.io/": net/http: TLS handshake timeout - retrying in 20s
2023-10-19T14:28:33-05:00 ERROR [ip getter] Get "https://ipinfo.io/": net/http: TLS handshake timeout - retrying in 40s
2023-10-19T14:29:13-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-19T14:29:14-05:00 ERROR [vpn] port forwarding for the first time: getting external IPv4 address: executing remote procedure call: connection timeout: after 2m7.75s
2023-10-19T14:29:14-05:00 INFO [vpn] starting
2023-10-19T14:29:14-05:00 INFO [firewall] allowing VPN connection...
2023-10-19T14:29:14-05:00 INFO [wireguard] Using available kernelspace implementation
2023-10-19T14:29:14-05:00 INFO [wireguard] Connecting to REDACTED:51820
2023-10-19T14:29:14-05:00 INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2023-10-19T14:29:15-05:00 INFO [port forwarding] starting
2023-10-19T14:29:15-05:00 INFO [healthcheck] healthy!
2023-10-19T14:29:15-05:00 INFO [port forwarding] gateway external IPv4 address is REDACTED
2023-10-19T14:29:15-05:00 INFO [port forwarding] port forwarded is REDACTED
2023-10-19T14:29:15-05:00 INFO [firewall] setting allowed input port REDACTED through interface tun0...
2023-10-19T14:29:15-05:00 INFO [port forwarding] writing port file /gluetun/forwarded_port
2023-10-19T14:29:15-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-19T14:34:40-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:34:48-05:00 INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
2023-10-19T14:34:48-05:00 INFO [vpn] stopping
2023-10-19T14:34:48-05:00 INFO [port forwarding] stopping
2023-10-19T14:34:48-05:00 INFO [firewall] removing allowed port REDACTED...
2023-10-19T14:34:48-05:00 INFO [port forwarding] removing port file /gluetun/forwarded_port
2023-10-19T14:34:48-05:00 INFO [vpn] starting
2023-10-19T14:34:48-05:00 INFO [firewall] allowing VPN connection...
2023-10-19T14:34:48-05:00 INFO [wireguard] Using available kernelspace implementation
2023-10-19T14:34:48-05:00 INFO [wireguard] Connecting to REDACTED:51820
2023-10-19T14:34:48-05:00 INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2023-10-19T14:34:48-05:00 INFO [port forwarding] starting
2023-10-19T14:34:49-05:00 INFO [port forwarding] gateway external IPv4 address is REDACTED
2023-10-19T14:34:50-05:00 INFO [port forwarding] port forwarded is REDACTED
2023-10-19T14:34:50-05:00 INFO [firewall] setting allowed input port REDACTED through interface tun0...
2023-10-19T14:34:50-05:00 INFO [port forwarding] writing port file /gluetun/forwarded_port
2023-10-19T14:34:50-05:00 INFO [healthcheck] healthy!
2023-10-19T14:34:58-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:35:00-05:00 INFO [healthcheck] healthy!
2023-10-19T14:35:03-05:00 ERROR [ip getter] Get "https://ipinfo.io/": context deadline exceeded (Client.Timeout exceeded while awaiting headers) - retrying in 5s
2023-10-19T14:35:10-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-19T14:35:41-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T14:35:43-05:00 INFO [healthcheck] healthy!
2023-10-19T14:36:36-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T15:25:20-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-19T15:25:25-05:00 INFO [healthcheck] healthy!
2023-10-19T15:37:05-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T16:37:14-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T17:10:54-05:00 INFO [dns] downloading DNS over TLS cryptographic files
2023-10-19T17:10:59-05:00 INFO [dns] downloading hostnames and IP block lists
2023-10-19T17:11:02-05:00 INFO [dns] stopping
2023-10-19T17:11:02-05:00 INFO [dns] using plaintext DNS at address 1.1.1.1
2023-10-19T17:11:02-05:00 INFO [dns] starting
2023-10-19T17:11:02-05:00 INFO [dns] downloading DNS over TLS cryptographic files
2023-10-19T17:11:02-05:00 INFO [dns] downloading hostnames and IP block lists
2023-10-19T17:11:09-05:00 INFO [dns] init module 0: validator
2023-10-19T17:11:09-05:00 INFO [dns] init module 1: iterator
2023-10-19T17:11:09-05:00 INFO [dns] start of service (unbound 1.17.1).
2023-10-19T17:11:10-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T17:11:10-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T17:11:10-05:00 INFO [dns] ready
2023-10-19T17:42:24-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-19T17:42:26-05:00 INFO [healthcheck] healthy!
2023-10-19T18:14:45-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T19:16:44-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T20:17:49-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T21:18:10-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T21:28:54-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-19T21:28:55-05:00 INFO [healthcheck] healthy!
2023-10-19T22:18:31-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-19T23:18:52-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T00:19:13-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T01:19:34-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T02:19:55-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T02:35:11-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-20T03:20:02-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T04:20:37-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T05:20:58-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T06:21:19-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T07:21:40-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T08:22:01-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T09:22:22-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T10:22:43-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T11:23:04-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T12:23:25-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T13:04:46-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-20T13:04:47-05:00 INFO [healthcheck] healthy!
2023-10-20T13:11:10-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-20T13:11:13-05:00 INFO [healthcheck] healthy!
2023-10-20T13:23:46-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T13:25:04-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-20T13:25:05-05:00 INFO [healthcheck] healthy!
2023-10-20T13:31:59-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-20T13:32:00-05:00 INFO [healthcheck] healthy!
2023-10-20T13:36:54-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-20T13:36:55-05:00 INFO [healthcheck] healthy!
2023-10-20T13:47:44-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-20T13:47:45-05:00 INFO [healthcheck] healthy!
2023-10-20T14:14:45-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-20T14:14:47-05:00 INFO [healthcheck] healthy!
2023-10-20T14:24:07-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T14:35:13-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-20T15:24:28-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T16:25:57-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T17:11:10-05:00 INFO [dns] downloading DNS over TLS cryptographic files
2023-10-20T17:11:15-05:00 INFO [dns] downloading hostnames and IP block lists
2023-10-20T17:11:18-05:00 INFO [dns] stopping
2023-10-20T17:11:18-05:00 INFO [dns] using plaintext DNS at address 1.1.1.1
2023-10-20T17:11:18-05:00 INFO [dns] starting
2023-10-20T17:11:18-05:00 INFO [dns] downloading DNS over TLS cryptographic files
2023-10-20T17:11:18-05:00 INFO [dns] downloading hostnames and IP block lists
2023-10-20T17:11:25-05:00 INFO [dns] init module 0: validator
2023-10-20T17:11:25-05:00 INFO [dns] init module 1: iterator
2023-10-20T17:11:25-05:00 INFO [dns] start of service (unbound 1.17.1).
2023-10-20T17:11:25-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T17:11:25-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T17:11:26-05:00 INFO [dns] ready
2023-10-20T18:16:19-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T19:20:01-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T20:26:00-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T21:29:54-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T21:29:54-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T22:30:43-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-20T23:31:01-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T00:31:33-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T01:32:31-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T02:32:49-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T02:35:15-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-21T03:32:54-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T04:32:59-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T05:33:04-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T06:33:09-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T07:33:14-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T08:33:19-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T09:33:24-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T10:33:29-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T11:33:34-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T12:32:41-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-21T12:32:42-05:00 INFO [healthcheck] healthy!
2023-10-21T12:33:39-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T13:33:44-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T14:33:49-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T14:35:16-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-21T15:33:54-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T16:33:59-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T17:11:26-05:00 INFO [dns] downloading DNS over TLS cryptographic files
2023-10-21T17:11:30-05:00 INFO [dns] downloading hostnames and IP block lists
2023-10-21T17:11:34-05:00 INFO [dns] stopping
2023-10-21T17:11:34-05:00 INFO [dns] using plaintext DNS at address 1.1.1.1
2023-10-21T17:11:34-05:00 INFO [dns] starting
2023-10-21T17:11:34-05:00 INFO [dns] downloading DNS over TLS cryptographic files
2023-10-21T17:11:34-05:00 INFO [dns] downloading hostnames and IP block lists
2023-10-21T17:11:41-05:00 INFO [dns] init module 0: validator
2023-10-21T17:11:41-05:00 INFO [dns] init module 1: iterator
2023-10-21T17:11:41-05:00 INFO [dns] start of service (unbound 1.17.1).
2023-10-21T17:11:41-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T17:11:41-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T17:11:42-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
2023-10-21T17:11:42-05:00 INFO [dns] ready
2023-10-21T17:11:43-05:00 INFO [healthcheck] healthy!
2023-10-21T18:13:44-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T19:14:18-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T20:14:42-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T21:15:19-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T22:15:54-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-21T23:16:34-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T00:17:20-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T01:17:47-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T02:18:03-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T02:35:18-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-22T03:18:22-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T04:18:42-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T05:18:53-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T06:19:09-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T07:19:21-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T08:19:37-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T09:19:47-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T10:15:27-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-22T10:15:30-05:00 INFO [healthcheck] healthy!
2023-10-22T10:20:02-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T10:45:10-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-22T10:45:11-05:00 INFO [healthcheck] healthy!
2023-10-22T11:20:13-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T12:06:43-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-22T12:06:44-05:00 INFO [healthcheck] healthy!
2023-10-22T12:20:35-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T13:20:50-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T14:21:05-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T14:35:19-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-22T15:21:20-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T16:21:33-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T17:11:42-05:00 INFO [dns] downloading DNS over TLS cryptographic files
2023-10-22T17:11:47-05:00 INFO [dns] downloading hostnames and IP block lists
2023-10-22T17:11:50-05:00 INFO [dns] stopping
2023-10-22T17:11:50-05:00 INFO [dns] using plaintext DNS at address 1.1.1.1
2023-10-22T17:11:50-05:00 INFO [dns] starting
2023-10-22T17:11:50-05:00 INFO [dns] downloading DNS over TLS cryptographic files
2023-10-22T17:11:50-05:00 INFO [dns] downloading hostnames and IP block lists
2023-10-22T17:11:52-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com on 127.0.0.1:53: read udp 127.0.0.1:57666->127.0.0.1:53: read: connection refused
2023-10-22T17:11:56-05:00 INFO [dns] init module 0: validator
2023-10-22T17:11:56-05:00 INFO [dns] init module 1: iterator
2023-10-22T17:11:56-05:00 INFO [dns] start of service (unbound 1.17.1).
2023-10-22T17:11:57-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T17:11:57-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T17:11:57-05:00 INFO [dns] ready
2023-10-22T17:11:58-05:00 INFO [healthcheck] healthy!
2023-10-22T18:14:48-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T19:16:20-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T20:16:33-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T21:20:02-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T22:21:15-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-22T23:21:20-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T00:21:25-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T01:21:30-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T02:21:35-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T02:35:21-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-23T03:21:40-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T04:21:45-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T05:21:50-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T06:21:55-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T07:22:00-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T08:22:05-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T09:26:06-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T10:26:43-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T10:58:28-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.133.229:443: i/o timeout
2023-10-23T10:58:29-05:00 INFO [healthcheck] healthy!
2023-10-23T10:59:22-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4 104.16.132.229:443: i/o timeout
2023-10-23T10:59:28-05:00 INFO [healthcheck] healthy!
2023-10-23T11:27:01-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T12:33:32-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T13:38:51-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T14:35:22-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-23T14:40:48-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T15:49:08-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T16:53:39-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T17:11:57-05:00 INFO [dns] downloading DNS over TLS cryptographic files
2023-10-23T17:12:02-05:00 INFO [dns] downloading hostnames and IP block lists
2023-10-23T17:12:04-05:00 INFO [dns] stopping
2023-10-23T17:12:04-05:00 INFO [dns] using plaintext DNS at address 1.1.1.1
2023-10-23T17:12:04-05:00 INFO [dns] starting
2023-10-23T17:12:04-05:00 INFO [dns] downloading DNS over TLS cryptographic files
2023-10-23T17:12:05-05:00 INFO [dns] downloading hostnames and IP block lists
2023-10-23T17:12:10-05:00 INFO [dns] init module 0: validator
2023-10-23T17:12:10-05:00 INFO [dns] init module 1: iterator
2023-10-23T17:12:10-05:00 INFO [dns] start of service (unbound 1.17.1).
2023-10-23T17:12:10-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T17:12:10-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T17:12:11-05:00 INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
2023-10-23T17:12:11-05:00 INFO [dns] ready
2023-10-23T17:12:12-05:00 INFO [healthcheck] healthy!
2023-10-23T18:16:22-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T18:16:22-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T19:19:21-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T20:20:10-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T21:20:53-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T22:21:06-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-23T23:21:23-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-24T00:21:55-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-24T01:22:11-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-24T02:22:33-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-24T02:35:24-05:00 INFO [ip getter] Public IP address is REDACTED
2023-10-24T03:22:58-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-24T04:23:09-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-24T04:33:20-05:00 INFO [firewall] removing allowed port REDACTED...
2023-10-24T04:33:20-05:00 INFO [port forwarding] removing port file /gluetun/forwarded_port
2023-10-24T04:33:20-05:00 ERROR [port forwarding] adding port mapping: executing remote procedure call: connection timeout: after 2m7.75s
2023-10-24T04:33:20-05:00 INFO [port forwarding] starting
2023-10-24T04:33:20-05:00 INFO [port forwarding] gateway external IPv4 address is REDACTED
2023-10-24T05:23:23-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
2023-10-24T06:23:31-05:00 INFO [dns] generate keytag query _ta-4a5c-4f66. NULL IN
```

**Comment by CplPwnies** [comment]
I am closing this issue because
1. It does not seem to be occurring anymore. Not sure if something changed in gluetun's code or if it was an issue on ProtonVPN's side. Either way, this particular issue seems to be pretty stable now.
2. This similar issue is being discussed heavily on #1882

**Comment by brunoorsolon** [comment]
Just to say that I was having this issue recently, it's not fully solved.
