### ISSUE TITLE
Bug: Private Internet Access AUTH_FAILED regression for tag v3.3.0

### ISSUE THREAD

**Issue by robgmills** [qdm12/gluetun#256]
**TLDR**: *Private Internet Access authentication fails on version v3.3.0 with minimal config values `VPNSP`, `USER`, and `PASSWORD`.  This issue is not present with the same `docker-compose.yaml` except for the image version.*

1. Is this urgent?

    - [ ] Yes
    - [x] No

2. What VPN service provider are you using?

    - [x] PIA
    - [ ] Mullvad
    - [ ] Windscribe
    - [ ] Surfshark
    - [ ] Cyberghost

3. What's the version of the program?

    **See the line at the top of your logs**

    `Running version v3.3.0 built on 2020-09-26T13:43:36Z (commit ecf7689)`

4. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information

Logs:

```log
vpn             | =========================================
vpn             | ================ Gluetun ================
vpn             | =========================================
vpn             | ==== A mix of OpenVPN, DNS over TLS, ====
vpn             | ======= Shadowsocks and Tinyproxy =======
vpn             | ========= all glued up with Go ==========
vpn             | =========================================
vpn             | =========== For tunneling to ============
vpn             | ======== your favorite VPN server =======
vpn             | =========================================
vpn             | === Made with ❤️  by github.com/qdm12 ====
vpn             | =========================================
vpn             |
vpn             | Running version v3.3.0 built on 2020-09-26T13:43:36Z (commit ecf7689)
vpn             |
vpn             | 📣  Update servers information see https://github.com/qdm12/gluetun/wiki/Update-servers-information
vpn             |
vpn             | 🔧  Need help? https://github.com/qdm12/gluetun/issues/new
vpn             | 💻  Email? quentin.mcgaw@gmail.com
vpn             | ☕  Slack? Join from the Slack button on Github
vpn             | 💸  Help me? https://github.com/sponsors/qdm12
vpn             | 2020-10-05T20:38:06.148-0500  INFO    OpenVPN version: 2.4.9
vpn             | 2020-10-05T20:38:06.167-0500  INFO    Unbound version: 1.10.1
vpn             | 2020-10-05T20:38:06.169-0500  INFO    IPtables version: v1.8.4
vpn             | 2020-10-05T20:38:06.193-0500  INFO    TinyProxy version: 1.10.0
vpn             | 2020-10-05T20:38:06.195-0500  INFO    Settings summary below:
vpn             | OpenVPN settings:
vpn             | |--User: [redacted]
vpn             | |--Password: [redacted]
vpn             | |--Verbosity level: 1
vpn             | |--Run as root: no
vpn             | |--Private Internet Access settings:
vpn             |  |--Network protocol: udp
vpn             |  |--Region: hungary
vpn             |  |--Encryption preset: strong
vpn             | System settings:
vpn             | |--User ID: 1000
vpn             | |--Group ID: 1000
vpn             | |--Timezone: america/chicago
vpn             | |--IP Status filepath: /tmp/gluetun/ip
vpn             | DNS over TLS settings:
vpn             |  |--DNS over TLS provider:
vpn             |   |--cloudflare
vpn             |  |--Caching: enabled
vpn             |  |--Block malicious: enabled
vpn             |  |--Block surveillance: disabled
vpn             |  |--Block ads: disabled
vpn             |  |--Allowed hostnames:
vpn             |   |--
vpn             |  |--Private addresses:
vpn             |   |--127.0.0.1/8
vpn             |   |--10.0.0.0/8
vpn             |   |--172.16.0.0/12
vpn             |   |--192.168.0.0/16
vpn             |   |--169.254.0.0/16
vpn             |   |--::1/128
vpn             |   |--fc00::/7
vpn             |   |--fe80::/10
vpn             |   |--::ffff:0:0/96
vpn             |  |--Verbosity level: 1/5
vpn             |  |--Verbosity details level: 0/4
vpn             |  |--Validation log level: 0/2
vpn             |  |--IPv6 resolution: disabled
vpn             |  |--Update: every 24h0m0s
vpn             |  |--Keep nameserver (disabled blocking): no
vpn             | Firewall settings:
vpn             |  |--Allowed subnets: 192.168.0.0/24
vpn             |  |--VPN input ports:
vpn             | TinyProxy settings: disabled
vpn             | ShadowSocks settings: disabled
vpn             | Public IP check period: 12h0m0s
vpn             | Version information: enabled
vpn             | Updater period: 24h0m0s
vpn             |
vpn             | 2020-10-05T20:38:06.304-0500  INFO    storage: Merging by most recent 6387 hardcoded servers and 6387 servers read from /gluetun/servers.json
vpn             | 2020-10-05T20:38:06.386-0500  INFO    routing: default route found: interface eth0, gateway 172.20.0.1
vpn             | 2020-10-05T20:38:06.386-0500  INFO    routing: local subnet found: 172.20.0.0/16
vpn             | 2020-10-05T20:38:06.386-0500  INFO    openvpn configurator: checking for device /dev/net/tun
vpn             | 2020-10-05T20:38:06.386-0500  WARN    TUN device is not available: open /dev/net/tun: no such file or directory
vpn             | 2020-10-05T20:38:06.386-0500  INFO    openvpn configurator: creating /dev/net/tun
vpn             | 2020-10-05T20:38:06.386-0500  INFO    firewall: enabling...
vpn             | 2020-10-05T20:38:06.442-0500  INFO    firewall: enabled successfully
vpn             | 2020-10-05T20:38:06.442-0500  INFO    firewall: setting allowed subnets through firewall...
vpn             | 2020-10-05T20:38:06.449-0500  INFO    routing: adding 192.168.0.0/24 as route via 172.20.0.1 eth0
vpn             | 2020-10-05T20:38:06.452-0500  INFO    http server: listening on 0.0.0.0:8000
vpn             | 2020-10-05T20:38:06.453-0500  INFO    Launching standard output merger
vpn             | 2020-10-05T20:38:06.453-0500  INFO    dns over tls: falling back on plaintext DNS at address 1.1.1.1
vpn             | 2020-10-05T20:38:06.453-0500  INFO    dns configurator: using DNS address 1.1.1.1 internally
vpn             | 2020-10-05T20:38:06.453-0500  INFO    dns configurator: using DNS address 1.1.1.1 system wide
vpn             | 2020-10-05T20:38:06.453-0500  INFO    firewall: setting VPN connections through firewall...
vpn             | 2020-10-05T20:38:06.455-0500  INFO    openvpn configurator: starting openvpn
vpn             | 2020-10-05T20:38:06.459-0500  INFO    openvpn: OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
vpn             | 2020-10-05T20:38:06.459-0500  INFO    openvpn: library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
vpn             | 2020-10-05T20:38:06.462-0500  INFO    openvpn: CRL: loaded 1 CRLs from file [[INLINE]]
vpn             | 2020-10-05T20:38:06.463-0500  INFO    openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]217.138.192.222:1197
vpn             | 2020-10-05T20:38:06.464-0500  INFO    openvpn: UDP link local: (not bound)
vpn             | 2020-10-05T20:38:06.466-0500  INFO    openvpn: UDP link remote: [AF_INET]217.138.192.222:1197
vpn             | 2020-10-05T20:38:07.704-0500  WARN    openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1570', remote='link-mtu 1542'
vpn             | 2020-10-05T20:38:07.704-0500  WARN    openvpn: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher BF-CBC'
vpn             | 2020-10-05T20:38:07.704-0500  WARN    openvpn: 'auth' is used inconsistently, local='auth SHA256', remote='auth SHA1'
vpn             | 2020-10-05T20:38:07.705-0500  WARN    openvpn: 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128'
vpn             | 2020-10-05T20:38:07.705-0500  INFO    openvpn: [budapest401] Peer Connection Initiated with [AF_INET]217.138.192.222:1197
vpn             | 2020-10-05T20:38:08.898-0500  INFO    openvpn: AUTH: Received control message: AUTH_FAILED
vpn             | 2020-10-05T20:38:08.898-0500  INFO    openvpn: SIGUSR1[soft,auth-failure] received, process restarting
vpn             | 2020-10-05T20:38:18.870-0500  INFO    openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]217.138.192.222:1197
vpn             | 2020-10-05T20:38:18.870-0500  INFO    openvpn: UDP link local: (not bound)
vpn             | 2020-10-05T20:38:18.870-0500  INFO    openvpn: UDP link remote: [AF_INET]217.138.192.222:1197
vpn             | 2020-10-05T20:38:19.671-0500  WARN    openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1570', remote='link-mtu 1542'
vpn             | 2020-10-05T20:38:19.672-0500  WARN    openvpn: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher BF-CBC'
vpn             | 2020-10-05T20:38:19.672-0500  WARN    openvpn: 'auth' is used inconsistently, local='auth SHA256', remote='auth SHA1'
vpn             | 2020-10-05T20:38:19.674-0500  WARN    openvpn: 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128'
vpn             | 2020-10-05T20:38:19.675-0500  INFO    openvpn: [budapest401] Peer Connection Initiated with [AF_INET]217.138.192.222:1197
vpn             | 2020-10-05T20:38:21.006-0500  INFO    openvpn: AUTH: Received control message: AUTH_FAILED
vpn             | 2020-10-05T20:38:21.007-0500  INFO    openvpn: SIGUSR1[soft,auth-failure] received, process restarting
```

Configuration file:

```yml
version: "3.8"
services:
  vpn:
    container_name: vpn
    image: qmcgaw/private-internet-access:v3.3.0
    ports:
      - 8000:8000/tcp
    volumes:
      - ${DOCKER_DATA_PATH}/vpn:/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      VPNSP: "private internet access"
      USER: ${VPN_USER}
      PASSWORD: ${VPN_PASSWORD}
    restart: unless-stopped
```

Host OS: macOS Catalina 10.15.6

**Comment by robgmills** [comment]
Stellar project. Thanks for sharing.

**Comment by robgmills** [comment]
Here's a working config and log using the `v3.2.0` tag:

Configuration file:

```yaml
version: "3.8"
services:
  vpn:
    container_name: vpn
    image: qmcgaw/private-internet-access:v3.2.0
    ports:
      - 8000:8000/tcp
    volumes:
      - ${DOCKER_DATA_PATH}/vpn:/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      VPNSP: "private internet access"
      USER: ${VPN_USER}
      PASSWORD: ${VPN_PASSWORD}
    restart: unless-stopped
```

Logs:

```
vpn    | =========================================
vpn    | ================ Gluetun ================
vpn    | =========================================
vpn    | ==== A mix of OpenVPN, DNS over TLS, ====
vpn    | ======= Shadowsocks and Tinyproxy =======
vpn    | ========= all glued up with Go ==========
vpn    | =========================================
vpn    | =========== For tunneling to ============
vpn    | ======== your favorite VPN server =======
vpn    | =========================================
vpn    | === Made with ❤️  by github.com/qdm12 ====
vpn    | =========================================
vpn    |
vpn    | Running version v3.2.0 built on 2020-08-25T23:31:57Z (commit 6fc2b3d)
vpn    |
vpn    |
vpn    | 🔧  Need help? https://github.com/qdm12/gluetun/issues/new
vpn    | 💻  Email? quentin.mcgaw@gmail.com
vpn    | ☕  Slack? Join from the Slack button on Github
vpn    | 💸  Help me? https://github.com/sponsors/qdm12
vpn    | 2020-10-06T00:46:17.009Z       INFO    IPtables version: v1.8.4
vpn    | 2020-10-06T00:46:17.048Z       INFO    TinyProxy version: 1.10.0
vpn    | 2020-10-06T00:46:17.055Z       INFO    OpenVPN version: 2.4.9
vpn    | 2020-10-06T00:46:17.058Z       INFO    Unbound version: 1.10.1
vpn    | 2020-10-06T00:46:17.059Z       INFO    Settings summary below:
vpn    | OpenVPN settings:
vpn    | |--User: [redacted]
vpn    | |--Password: [redacted]
vpn    | |--Verbosity level: 1
vpn    | |--Run as root: no
vpn    | |--Private Internet Access settings:
vpn    |  |--Network protocol: udp
vpn    |  |--Region:
vpn    |  |--Encryption preset: strong
vpn    |  |--Port forwarding: off
vpn    | System settings:
vpn    | |--User ID: 1000
vpn    | |--Group ID: 1000
vpn    | |--Timezone:
vpn    | |--IP Status filepath: /tmp/gluetun/ip
vpn    | DNS over TLS settings:
vpn    |  |--DNS over TLS provider:
vpn    |   |--cloudflare
vpn    |  |--Caching: enabled
vpn    |  |--Block malicious: enabled
vpn    |  |--Block surveillance: disabled
vpn    |  |--Block ads: disabled
vpn    |  |--Allowed hostnames:
vpn    |   |--
vpn    |  |--Private addresses:
vpn    |   |--127.0.0.1/8
vpn    |   |--10.0.0.0/8
vpn    |   |--172.16.0.0/12
vpn    |   |--192.168.0.0/16
vpn    |   |--169.254.0.0/16
vpn    |   |--::1/128
vpn    |   |--fc00::/7
vpn    |   |--fe80::/10
vpn    |   |--::ffff:0:0/96
vpn    |  |--Verbosity level: 1/5
vpn    |  |--Verbosity details level: 0/4
vpn    |  |--Validation log level: 0/2
vpn    |  |--IPv6 resolution: disabled
vpn    |  |--Update: every 24h0m0s
vpn    |  |--Keep nameserver (disabled blocking): no
vpn    | Firewall settings:
vpn    |  |--Allowed subnets:
vpn    |  |--VPN input ports:
vpn    | TinyProxy settings: disabled
vpn    | ShadowSocks settings: disabled
vpn    | Public IP check period: 12h0m0s
vpn    |
vpn    | 2020-10-06T00:46:17.061Z       INFO    routing: default route found: interface eth0, gateway 172.20.0.1
vpn    | 2020-10-06T00:46:17.061Z       INFO    routing: local subnet found: 172.20.0.0/16
vpn    | 2020-10-06T00:46:17.061Z       INFO    openvpn configurator: checking for device /dev/net/tun
vpn    | 2020-10-06T00:46:17.062Z       WARN    TUN device is not available: open /dev/net/tun: no such file or directory
vpn    | 2020-10-06T00:46:17.063Z       INFO    openvpn configurator: creating /dev/net/tun
vpn    | 2020-10-06T00:46:17.065Z       INFO    Launching standard output merger
vpn    | 2020-10-06T00:46:17.065Z       INFO    firewall: enabling...
vpn    | 2020-10-06T00:46:17.140Z       INFO    firewall: enabled successfully
vpn    | 2020-10-06T00:46:17.140Z       INFO    firewall: setting allowed subnets through firewall...
vpn    | 2020-10-06T00:46:17.141Z       INFO    dns over tls: falling back on plaintext DNS at address 1.1.1.1
vpn    | 2020-10-06T00:46:17.141Z       INFO    dns configurator: using DNS address 1.1.1.1 internally
vpn    | 2020-10-06T00:46:17.141Z       INFO    dns configurator: using DNS address 1.1.1.1 system wide
vpn    | 2020-10-06T00:46:17.142Z       INFO    http server: listening on 0.0.0.0:8000
vpn    | 2020-10-06T00:46:17.145Z       INFO    firewall: setting VPN connections through firewall...
vpn    | 2020-10-06T00:46:17.346Z       INFO    openvpn configurator: starting openvpn
vpn    | 2020-10-06T00:46:17.349Z       INFO    openvpn: OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
vpn    | 2020-10-06T00:46:17.350Z       INFO    openvpn: library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
vpn    | 2020-10-06T00:46:17.357Z       INFO    openvpn: CRL: loaded 1 CRLs from file [[INLINE]]
vpn    | 2020-10-06T00:46:17.359Z       INFO    openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]185.104.186.26:1197
vpn    | 2020-10-06T00:46:17.359Z       INFO    openvpn: UDP link local: (not bound)
vpn    | 2020-10-06T00:46:17.359Z       INFO    openvpn: UDP link remote: [AF_INET]185.104.186.26:1197
vpn    | 2020-10-06T00:47:17.584Z       INFO    openvpn: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
vpn    | 2020-10-06T00:47:17.584Z       INFO    openvpn: TLS Error: TLS handshake failed
vpn    | 2020-10-06T00:47:17.585Z       INFO    openvpn: SIGUSR1[soft,tls-error] received, process restarting
vpn    | 2020-10-06T00:47:27.558Z       INFO    openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]185.232.21.27:1197
vpn    | 2020-10-06T00:47:27.558Z       INFO    openvpn: UDP link local: (not bound)
vpn    | 2020-10-06T00:47:27.558Z       INFO    openvpn: UDP link remote: [AF_INET]185.232.21.27:1197
vpn    | 2020-10-06T00:48:27.222Z       INFO    openvpn: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
vpn    | 2020-10-06T00:48:27.223Z       INFO    openvpn: TLS Error: TLS handshake failed
vpn    | 2020-10-06T00:48:27.223Z       INFO    openvpn: SIGUSR1[soft,tls-error] received, process restarting
vpn    | 2020-10-06T00:48:37.225Z       INFO    openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]156.146.60.129:1197
vpn    | 2020-10-06T00:48:37.225Z       INFO    openvpn: UDP link local: (not bound)
vpn    | 2020-10-06T00:48:37.226Z       INFO    openvpn: UDP link remote: [AF_INET]156.146.60.129:1197
vpn    | 2020-10-06T00:48:37.800Z       WARN    openvpn: 'link-mtu' is used inconsistently, local='link-mtu 1570', remote='link-mtu 1542'
vpn    | 2020-10-06T00:48:37.801Z       WARN    openvpn: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher BF-CBC'
vpn    | 2020-10-06T00:48:37.801Z       WARN    openvpn: 'auth' is used inconsistently, local='auth SHA256', remote='auth SHA1'
vpn    | 2020-10-06T00:48:37.801Z       WARN    openvpn: 'keysize' is used inconsistently, local='keysize 256', remote='keysize 128'
vpn    | 2020-10-06T00:48:37.802Z       INFO    openvpn: [38629721cd64277ceabcd4da6381540d] Peer Connection Initiated with [AF_INET]156.146.60.129:1197
vpn    | 2020-10-06T00:48:38.984Z       INFO    openvpn: TUN/TAP device tun0 opened
vpn    | 2020-10-06T00:48:38.986Z       INFO    openvpn: /sbin/ip link set dev tun0 up mtu 1500
vpn    | 2020-10-06T00:48:38.988Z       INFO    openvpn: /sbin/ip addr add dev tun0 local 10.68.10.6 peer 10.68.10.5
vpn    | 2020-10-06T00:48:38.998Z       INFO    openvpn: UID set to nonrootuser
vpn    | 2020-10-06T00:48:38.998Z       INFO    openvpn: Initialization Sequence Completed
vpn    | 2020-10-06T00:48:38.999Z       INFO    dns configurator: downloading root hints from https://raw.githubusercontent.com/qdm12/files/master/named.root.updated
vpn    | 2020-10-06T00:48:39.000Z       INFO    routing: default route found: interface eth0, gateway 172.20.0.1
vpn    | 2020-10-06T00:48:39.004Z       INFO    Gateway VPN IP address: 156.146.60.129
vpn    | 2020-10-06T00:48:39.695Z       INFO    ip getter: Public IP address is 156.146.60.129
vpn    | 2020-10-06T00:48:39.880Z       INFO    dns configurator: downloading root key from https://raw.githubusercontent.com/qdm12/files/master/root.key.updated
vpn    | 2020-10-06T00:48:40.018Z       INFO    dns configurator: generating Unbound configuration
vpn    | 2020-10-06T00:48:41.295Z       INFO    dns configurator: 61358 hostnames blocked overall
vpn    | 2020-10-06T00:48:41.296Z       INFO    dns configurator: 2581 IP addresses blocked overall
vpn    | 2020-10-06T00:48:41.364Z       INFO    dns configurator: starting unbound
vpn    | 2020-10-06T00:48:41.365Z       INFO    dns configurator: using DNS address 127.0.0.1 internally
vpn    | 2020-10-06T00:48:41.365Z       INFO    dns configurator: using DNS address 127.0.0.1 system wide
vpn    | 2020-10-06T00:48:41.629Z       INFO    unbound: init module 0: validator
vpn    | 2020-10-06T00:48:41.630Z       INFO    unbound: init module 1: iterator
vpn    | 2020-10-06T00:48:41.681Z       INFO    unbound: start of service (unbound 1.10.1).
vpn    | 2020-10-06T00:48:42.168Z       INFO    unbound: generate keytag query _ta-4a5c-4f66. NULL IN
```

And here's 2 tests to show that it works as I'd expect:

```sh
 docker exec -it vpn wget -qO- https://ipinfo.io 
{
  "ip": "156.146.60.129",
  "hostname": "unn-156-146-60-129.cdn77.com",
  "city": "Vienna",
  "region": "Vienna",
  "country": "AT",
  "loc": "48.2085,16.3721",
  "org": "AS60068 Datacamp Limited",
  "postal": "1010",
  "timezone": "Europe/Vienna",
  "readme": "https://ipinfo.io/missingauth"
}%
```

```sh
docker run --rm --network=container:vpn alpine:3.12 wget -qO- https://ipinfo.io
{
  "ip": "156.146.60.129",
  "hostname": "unn-156-146-60-129.cdn77.com",
  "city": "Vienna",
  "region": "Vienna",
  "country": "AT",
  "loc": "48.2085,16.3721",
  "org": "AS60068 Datacamp Limited",
  "postal": "1010",
  "timezone": "Europe/Vienna",
  "readme": "https://ipinfo.io/missingauth"
}%
```

**Comment by qdm12** [comment]
Thanks for the detailed issue!

The big difference I can think of between 3.2 and 3.3 is that 3.3 is using the newer v4 PIA servers. (v3 older servers are going down at the end of the month).

Can you try

1. With another region on 3.3.0
1. With `VPNSP=private internet access old` on 3.3.0
1. With `qmcgaw/private-internet-access:latest` see if it works?

AUTH_FAILED definitely means we reach the VPN server but our credentials don't work. It could eventually be an issue on the new PIA servers too, let's see.

**Comment by robgmills** [comment]
Wow!  Quick response!

0. I've now tried with the following regions: `Hungary`, `Vienna`, `Ukraine`, `US Chicago`, and `DE Berlin` and all receive the same error.
0. Using the combination of `v3.3.0` and `VPNSP=private internet access old` seems to work!
0. Using `qmcgaw/private-internet-access:latest` fails if I use `VPNSP=private internet access` but does work if I do use `VPNSP=private internet access old`.

Hope this helps and sorry for the false alarm if it's really a PIA issue!

**Comment by ZerNico** [comment]
@robgmills I have tried the same configuration, for me it works fine. Tried a few different regions and they all seem to work.
`v3.3.0` and `VPNSP=private internet access`

**Comment by qdm12** [comment]
Most users didn't seem (including me) to have trouble moving from the old (v3) servers to the v4 servers, as @ZerNico mentions.

Maybe try changing your credentials or ask PIA support why your credentials don't work on the newer servers, as older v3 servers are going offline at the end of the month. Please let me know what's the outcome, it might be useful for other people too.

**Comment by robgmills** [comment]
Oh man.  I think this was a total _PEBKAC_ error.  🤦 

In my previous configuration I'd been using the _PPTP/L2TP/SOCKS Username and Password_ found in the PIA client control panel and set those to their respective environment variables.  Changing those values to my PIA account username and password seems to have resolved the issue and I'm able to use the combination of `VPNSP=private internet access` and `qmcgaw/private-internet-access:v3.3.0` (or `:latest`).

I guess the issue is that I'm not super up-to-date on the differences between the PIA v3 and v4 servers ("NextGen" network) or the differences between WireGuard and PPTP.  Sorry if this should have been apparent to me and for the false alarm!

**Comment by qdm12** [comment]
Glad you figured it out. So just to be clear on their v3 servers, you could use the same credentials across their tunnel protocols, which is not the case with their v4 servers? 🤔

**Comment by 0xE232FE** [comment]
Still trouble with Pia Nextgen Server. I am escalating it at the Pia Support. Because the OpenVPN Client also don't work on Windows/Linux and Mac. Its not a gluetun issue it seems to be a Pia Issue. :-/ We can not do anything about it until they fix it on their side.

**Comment by qdm12** [comment]
Ok let me know, I'm in touch with a PIA engineer maybe I can ping him on that if support doesn't answer in the next few days.

**Comment by originell** [comment]
I'm running into the very same issue. Drove me nuts until I found this issue.

Tried:

- PPTP credentials
- the actual ones,… 
- I even tried their ovpn generator with `dperson/openvpn-client`, to verify I'm not crazy.

haven't tried it with actual ovpn on my computer yet. weirdly enough PIA app itself works, openvpn and wireguard proto.

**Comment by qdm12** [comment]
Let's keep this opened for whoever gets that bug too.

**Comment by 0xE232FE** [comment]
On my Linux Test Server I've a connection loop, which tries to connect to the DE Berlin Endpoint since yesterday 4:00pm. And it gets two times of 60 tries "Initialization Sequence Completed" in the last 60 Minutes. The loop always uses same config and it succeeded on Endpoint 154.13.1.131:1197 and 154.13.1.141:1197. But actually getting AUTH Errors over and over again. :-(

**Comment by qdm12** [comment]
Thanks @0xE232FE Although gluetun still uses 2.4.9 (from Alpine [here](https://pkgs.alpinelinux.org/packages?name=openvpn&branch=v3.12&repo=main&arch=x86_64)) and I think has been doing so for a while. I'll double check tomorrow that it's using 2.4.9.

**Comment by qdm12** [comment]
Can you guys please try the image with tag `:pia-auth-fails`? It's using openvpn 2.4.8 instead of 2.4.9, although I doubt this will solve it as it's meant to be a bug fix only. Let me know, and we can try with openvpn 2.3.x if that doesn't work.

**Comment by illiteratealliterator** [comment]
No luck for me I'm afraid, same result as before:
```
INFO    openvpn: OpenVPN 2.4.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Feb  7 2020
INFO    openvpn: library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
INFO    openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]180.92.192.156:1197
INFO    openvpn: UDP link local: (not bound)
INFO    openvpn: UDP link remote: [AF_INET]180.92.192.156:1197
INFO    openvpn: [sydney403] Peer Connection Initiated with [AF_INET]180.92.192.156:1197
ERROR   openvpn: AUTH: Received control message: AUTH_FAILED
```

**Comment by qdm12** [comment]
Alright thanks for the quick response! I just pushed another image (again with tag `:pia-auth-fails`, using openvpn 2.3.18, although that's really dated. I doubt this has to do with the client openvpn version. Also, just to be certain, this only occurs on some of the regions and not all right?

**Comment by illiteratealliterator** [comment]
No luck on that one either, but for a different reason I think... 

```
gluetun    | 2020-11-19T14:02:30.296+1000       INFO    storage: Merging by most recent 6734 hardcoded servers and 0 servers read from /gluetun/servers.json
gluetun    | 2020-11-19T14:02:30.311+1000       INFO    routing: default route found: interface eth0, gateway 192.168.32.1
gluetun    | 2020-11-19T14:02:30.311+1000       INFO    routing: local subnet found: 192.168.32.0/20
gluetun    | 2020-11-19T14:02:30.311+1000       INFO    routing: default route found: interface eth0, gateway 192.168.32.1
gluetun    | 2020-11-19T14:02:30.311+1000       INFO    routing: adding route for 0.0.0.0/0
gluetun    | 2020-11-19T14:02:30.311+1000       INFO    firewall: firewall disabled, only updating allowed subnets internal list
gluetun    | 2020-11-19T14:02:30.312+1000       INFO    routing: default route found: interface eth0, gateway 192.168.32.1
gluetun    | 2020-11-19T14:02:30.312+1000       INFO    routing: adding route for 10.0.0.0/8
gluetun    | 2020-11-19T14:02:30.312+1000       INFO    openvpn configurator: checking for device /dev/net/tun
gluetun    | 2020-11-19T14:02:30.312+1000       WARN    TUN device is not available: open /dev/net/tun: no such file or directory
gluetun    | 2020-11-19T14:02:30.312+1000       INFO    openvpn configurator: creating /dev/net/tun
gluetun    | 2020-11-19T14:02:30.312+1000       INFO    firewall: enabling...
gluetun    | 2020-11-19T14:02:30.319+1000       INFO    firewall: enabled successfully
gluetun    | 2020-11-19T14:02:30.319+1000       INFO    Launching standard output merger
gluetun    | 2020-11-19T14:02:30.319+1000       INFO    http proxy: listening on 0.0.0.0:8888
gluetun    | 2020-11-19T14:02:30.319+1000       INFO    http server: listening on 0.0.0.0:8000
gluetun    | 2020-11-19T14:02:30.319+1000       INFO    healthcheck: listening on 127.0.0.1:9999
gluetun    | 2020-11-19T14:02:30.319+1000       INFO    dns over tls: falling back on plaintext DNS at address 1.1.1.1
gluetun    | 2020-11-19T14:02:30.319+1000       INFO    firewall: setting VPN connection through firewall...
gluetun    | 2020-11-19T14:02:30.319+1000       INFO    dns configurator: using DNS address 1.1.1.1 internally
gluetun    | 2020-11-19T14:02:30.319+1000       INFO    dns configurator: using DNS address 1.1.1.1 system wide
gluetun    | 2020-11-19T14:02:30.321+1000       INFO    openvpn configurator: starting openvpn
gluetun    | 2020-11-19T14:02:30.323+1000       ERROR   openvpn: Unrecognized option or missing parameter(s) in /etc/openvpn/target.ovpn:8: compress (2.3.18)
gluetun    | 2020-11-19T14:02:30.323+1000       INFO    openvpn: Use --help for more information.
gluetun    | 2020-11-19T14:02:30.323+1000       ERROR   openvpn: exit status 1
gluetun    | 2020-11-19T14:02:30.323+1000       INFO    openvpn: retrying in 30s
gluetun    | 2020-11-19T14:02:30.323+1000       WARN    close |0: file already closed
gluetun    | 2020-11-19T14:03:00.323+1000       INFO    firewall: setting VPN connection through firewall...
gluetun    | 2020-11-19T14:03:00.323+1000       INFO    openvpn configurator: starting openvpn
gluetun    | 2020-11-19T14:03:00.326+1000       ERROR   openvpn: Unrecognized option or missing parameter(s) in /etc/openvpn/target.ovpn:8: compress (2.3.18)
gluetun    | 2020-11-19T14:03:00.326+1000       INFO    openvpn: Use --help for more information.
gluetun    | 2020-11-19T14:03:00.326+1000       ERROR   openvpn: exit status 1
gluetun    | 2020-11-19T14:03:00.326+1000       INFO    openvpn: retrying in 30s
gluetun    | 2020-11-19T14:03:00.326+1000       WARN    close |0: file already closed

```

I've only tried with the Sydney AU region, but I'll try some others now with :latest. Any regions in particular I should test?

**Comment by illiteratealliterator** [comment]
Ok, so I switched to the latest image, and tried it with AU Melbourne, and it worked immediately!

```
gluetun    | 2020-11-19T14:11:04.140+1000       INFO    openvpn configurator: checking for device /dev/net/tun
gluetun    | 2020-11-19T14:11:04.140+1000       WARN    TUN device is not available: open /dev/net/tun: no such file or directory
gluetun    | 2020-11-19T14:11:04.140+1000       INFO    openvpn configurator: creating /dev/net/tun
gluetun    | 2020-11-19T14:11:04.140+1000       INFO    firewall: enabling...
gluetun    | 2020-11-19T14:11:04.149+1000       INFO    firewall: enabled successfully
gluetun    | 2020-11-19T14:11:04.149+1000       INFO    Launching standard output merger
gluetun    | 2020-11-19T14:11:04.149+1000       INFO    dns over tls: falling back on plaintext DNS at address 1.1.1.1
gluetun    | 2020-11-19T14:11:04.149+1000       INFO    dns configurator: using DNS address 1.1.1.1 internally
gluetun    | 2020-11-19T14:11:04.149+1000       INFO    dns configurator: using DNS address 1.1.1.1 system wide
gluetun    | 2020-11-19T14:11:04.149+1000       INFO    http proxy: listening on 0.0.0.0:8888
gluetun    | 2020-11-19T14:11:04.149+1000       INFO    healthcheck: listening on 127.0.0.1:9999
gluetun    | 2020-11-19T14:11:04.149+1000       INFO    firewall: setting VPN connection through firewall...
gluetun    | 2020-11-19T14:11:04.150+1000       INFO    http server: listening on 0.0.0.0:8000
gluetun    | 2020-11-19T14:11:04.150+1000       INFO    openvpn configurator: starting openvpn
gluetun    | 2020-11-19T14:11:04.152+1000       INFO    openvpn: OpenVPN 2.4.9 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Apr 20 2020
gluetun    | 2020-11-19T14:11:04.152+1000       INFO    openvpn: library versions: OpenSSL 1.1.1g  21 Apr 2020, LZO 2.10
gluetun    | 2020-11-19T14:11:04.153+1000       INFO    openvpn: CRL: loaded 1 CRLs from file [[INLINE]]
gluetun    | 2020-11-19T14:11:04.154+1000       INFO    openvpn: TCP/UDP: Preserving recently used remote address: [AF_INET]27.50.74.148:1197
gluetun    | 2020-11-19T14:11:04.154+1000       INFO    openvpn: UDP link local: (not bound)
gluetun    | 2020-11-19T14:11:04.154+1000       INFO    openvpn: UDP link remote: [AF_INET]27.50.74.148:1197
gluetun    | 2020-11-19T14:11:04.478+1000       INFO    openvpn: [melbourne406] Peer Connection Initiated with [AF_INET]27.50.74.148:1197
gluetun    | 2020-11-19T14:11:05.639+1000       INFO    openvpn: OpenVPN ROUTE6: OpenVPN needs a gateway parameter for a --route-ipv6 option and no default was specified by either --route-ipv6-gateway or --ifconfig-ipv6 options
gluetun    | 2020-11-19T14:11:05.639+1000       INFO    openvpn: OpenVPN ROUTE: failed to parse/resolve route for host/network: 2000::/3
gluetun    | 2020-11-19T14:11:05.639+1000       INFO    openvpn: TUN/TAP device tun0 opened
gluetun    | 2020-11-19T14:11:05.639+1000       INFO    openvpn: /sbin/ip link set dev tun0 up mtu 1500
gluetun    | 2020-11-19T14:11:05.640+1000       INFO    openvpn: /sbin/ip addr add dev tun0 10.3.110.6/24 broadcast 10.3.110.255
gluetun    | 2020-11-19T14:11:05.642+1000       WARN    openvpn: OpenVPN was configured to add an IPv6 route over tun0. However, no IPv6 has been configured for this interface, therefore the route installation may fail or may not work as expected.
gluetun    | 2020-11-19T14:11:05.642+1000       INFO    openvpn: UID set to nonrootuser
gluetun    | 2020-11-19T14:11:05.642+1000       INFO    openvpn: Initialization Sequence Completed
gluetun    | 2020-11-19T14:11:05.643+1000       INFO    dns configurator: downloading root hints from https://raw.githubusercontent.com/qdm12/files/master/named.root.updated
gluetun    | 2020-11-19T14:11:05.643+1000       INFO    VPN routing IP address: 27.50.74.148
gluetun    | 2020-11-19T14:11:07.095+1000       INFO    dns configurator: downloading root key from https://raw.githubusercontent.com/qdm12/files/master/root.key.updated
gluetun    | 2020-11-19T14:11:07.127+1000       INFO    dns configurator: generating Unbound configuration
gluetun    | 2020-11-19T14:11:07.596+1000       INFO    dns configurator: 63001 hostnames blocked overall
gluetun    | 2020-11-19T14:11:07.596+1000       INFO    dns configurator: 2689 IP addresses blocked overall
gluetun    | 2020-11-19T14:11:07.624+1000       INFO    dns configurator: starting unbound
gluetun    | 2020-11-19T14:11:07.624+1000       INFO    dns configurator: using DNS address 127.0.0.1 internally
gluetun    | 2020-11-19T14:11:07.624+1000       INFO    dns configurator: using DNS address 127.0.0.1 system wide
gluetun    | 2020-11-19T14:11:07.766+1000       INFO    unbound: init module 0: validator
gluetun    | 2020-11-19T14:11:07.766+1000       INFO    unbound: init module 1: iterator
gluetun    | 2020-11-19T14:11:07.796+1000       INFO    unbound: start of service (unbound 1.10.1).
gluetun    | 2020-11-19T14:11:09.068+1000       INFO    unbound: generate keytag query _ta-4a5c-4f66. NULL IN
gluetun    | 2020-11-19T14:11:11.304+1000       INFO    dns over tls: DNS over TLS is ready
gluetun    | 2020-11-19T14:11:14.764+1000       INFO    ip getter: Public IP address is 27.50.74.148
gluetun    | 2020-11-19T14:11:18.125+1000       INFO    You are running on the bleeding edge of latest!
```

I imagine this means it's definitely something at PIA's end. I tried switching back to AU Sydney and it failed again immediately, then back to Melbourne and it worked again.... so doesn't appear random.

**Comment by originell** [comment]
Sucks :( Do you peeps want me to verify this as well? I'm usually using VPNs from the Europe region…

**Comment by 0xE232FE** [comment]
Europe I tested on:
- [UK London] had the Auth issue but actually its now fixed for this particular location.
- [Belgium] and [DE Berlin] still don't work for me. Fails with Auth Error.

Australia
- [AU Sydney] doesn't work for me too.
- [AU Melbourne] is working for me. Same with the European servers [DE Berlin] not working and [DE Frankfurt] working.

On OpenVPN Version 2.3.18 there is a error with the Compression Parameter on Versions previously to 2.4.x the compression was like **comp-lzo no** or **comp-lzo yes** Thats why you get different error but I was not able to connect with Version 2.3.18. And using more older Versions should be a security concern. Thats not professional handling of this error.

**Comment by qdm12** [comment]
Thanks for the detailed info @0xE232FE 

So that's definitely a PIA server issue I think. I removed the `compression` option, can you try pulling it and try again? At least that can help PIA support know that's it's not an openvpn version issue.

Or maybe it's the oppposite thing that what their support says: they upgraded some of their servers to openvpn 2.5.0 which don't support an older openvpn? Openvpn 2.5.0 is not available on Alpine but I could eventually do some gymnastics to build it from source to fix that.

**Comment by illiteratealliterator** [comment]
I tried the pia-auth-fails on AU Sydney again, but no luck. I think you're right, sounds like it's something at their end, like they haven't rolled out the same software to each region yet.

```
gluetun    | Running version pia-auth-fails built on 2020-11-19T13:45:33Z (commit 6555ea9)

gluetun    | 2020-11-20T09:08:38.677+1000       INFO    storage: Merging by most recent 6734 hardcoded servers and 0 servers read from /gluetun/servers.json
gluetun    | 2020-11-20T09:08:38.695+1000       INFO    routing: default route found: interface eth0, gateway 192.168.64.1
gluetun    | 2020-11-20T09:08:38.695+1000       INFO    routing: local subnet found: 192.168.64.0/20
gluetun    | 2020-11-20T09:08:38.695+1000       INFO    routing: default route found: interface eth0, gateway 192.168.64.1
gluetun    | 2020-11-20T09:08:38.695+1000       INFO    routing: adding route for 0.0.0.0/0
gluetun    | 2020-11-20T09:08:38.695+1000       INFO    firewall: firewall disabled, only updating allowed subnets internal list
gluetun    | 2020-11-20T09:08:38.695+1000       INFO    routing: default route found: interface eth0, gateway 192.168.64.1
gluetun    | 2020-11-20T09:08:38.695+1000       INFO    routing: adding route for 10.0.0.0/8
gluetun    | 2020-11-20T09:08:38.695+1000       INFO    openvpn configurator: checking for device /dev/net/tun
gluetun    | 2020-11-20T09:08:38.696+1000       WARN    TUN device is not available: open /dev/net/tun: no such file or directory
gluetun    | 2020-11-20T09:08:38.696+1000       INFO    openvpn configurator: creating /dev/net/tun
gluetun    | 2020-11-20T09:08:38.696+1000       INFO    firewall: enabling...
gluetun    | 2020-11-20T09:08:38.704+1000       INFO    firewall: enabled successfully
gluetun    | 2020-11-20T09:08:38.704+1000       INFO    Launching standard output merger
gluetun    | 2020-11-20T09:08:38.704+1000       INFO    dns over tls: falling back on plaintext DNS at address 1.1.1.1
gluetun    | 2020-11-20T09:08:38.704+1000       INFO    dns configurator: using DNS address 1.1.1.1 internally
gluetun    | 2020-11-20T09:08:38.704+1000       INFO    dns configurator: using DNS address 1.1.1.1 system wide
gluetun    | 2020-11-20T09:08:38.704+1000       INFO    http server: listening on 0.0.0.0:8000
gluetun    | 2020-11-20T09:08:38.704+1000       INFO    healthcheck: listening on 127.0.0.1:9999
gluetun    | 2020-11-20T09:08:38.704+1000       INFO    http proxy: listening on 0.0.0.0:8888
gluetun    | 2020-11-20T09:08:38.705+1000       INFO    firewall: setting VPN connection through firewall...
gluetun    | 2020-11-20T09:08:38.706+1000       INFO    openvpn configurator: starting openvpn
gluetun    | 2020-11-20T09:08:38.709+1000       ERROR   openvpn: Unrecognized option or missing parameter(s) in /etc/openvpn/target.ovpn:10: pull-filter (2.3.18)
gluetun    | 2020-11-20T09:08:38.709+1000       INFO    openvpn: Use --help for more information.
gluetun    | 2020-11-20T09:08:38.709+1000       WARN    close |0: file already closed
gluetun    | 2020-11-20T09:08:38.709+1000       ERROR   openvpn: exit status 1
gluetun    | 2020-11-20T09:08:38.709+1000       INFO    openvpn: retrying in 30s
```

**Comment by qdm12** [comment]
Yeah I'm having trouble adapting it to support openvpn 2.3 as there is a lot of things that changed for its config, so screw that, especially since it's not really viable security wise.

On the other hand, I'm working on somehow compiling openvpn 2.5.0 from source, maybe that could solve it. I'll ping back here once I'm done.

**Comment by 0xE232FE** [comment]
DE Berlin has been fixed
Belgium still have issues.

**Comment by illiteratealliterator** [comment]
Reporting in... I gave "AU Sydney" another shot today and it's fixed too! Yay!

**Comment by qdm12** [comment]
Thanks everyone for keeping me updated. Sorry I got caught up in other work and couldn't finish that openvpn 2.5. Anyway, I doubt it would had solved it. Let's close the issue for now. Thanks!

**Comment by originell** [comment]
If anyone else is still having issues with connecting (I did): you might want to try using a PIA Token instead of your username/password!

Steps to retrieve your token and use it with gluetun:

1. Clone the [official PIA manual-connections repo](https://github.com/pia-foss/manual-connections/)
2. Fire up a terminal and run

    ```sh
    $ PIA_USER=p0123456 PIA_PASS=xxx ./get_region_and_token.sh
   ```

    You should see an output like this:

    ```
    {
        "status": "OK",
        "token": "d6E373Cdcaf204Bd5A0ACFd5bE36e5C53a88391caAFa7b7B6ad3CFb044BE00d8CE0Cc5429196cd5f341DECA26787045C4FDDaD8ABC7feb9fa21F1FFCc173"
    }
    This token will expire in 24 hours.
    ```
3. Copy the token. 
4. The first 62 characters of your token are your _username_. Everything after the 62nd character, is your _password_. ([source](https://github.com/pia-foss/manual-connections/blob/master/connect_to_openvpn_with_token.sh#L112-L113))

    The link shows you to some bash, but here's an equivalent in python:

    ```python
    $ python -c "token = 'd6E373Cdcaf204Bd5A0ACFd5bE36e5C53a88391caAFa7b7B6ad3CFb044BE00d8CE0Cc5429196cd5f341DECA26787045C4FDDaD8ABC7feb9fa21F1FFCc173'; print(token[:62]); print(token[62:])"
    d6E373Cdcaf204Bd5A0ACFd5bE36e5C53a88391caAFa7b7B6ad3CFb044BE00
    d8CE0Cc5429196cd5f341DECA26787045C4FDDaD8ABC7feb9fa21F1FFCc173
    ```
5. So our token above would be used like this with the `docker` cli:

    ```sh
     -e USER=d6E373Cdcaf204Bd5A0ACFd5bE36e5C53a88391caAFa7b7B6ad3CFb044BE00 \
     -e PASSWORD=d8CE0Cc5429196cd5f341DECA26787045C4FDDaD8ABC7feb9fa21F1FFCc173
    ```

    or in a `docker-compose.yml`:

    ```yaml
    environment:
      - VPNSP=private internet access
      - USER=d6E373Cdcaf204Bd5A0ACFd5bE36e5C53a88391caAFa7b7B6ad3CFb044BE00
      - PASSWORD=d8CE0Cc5429196cd5f341DECA26787045C4FDDaD8ABC7feb9fa21F1FFCc173
    ```

I stumbled over the [official pia repo](https://github.com/pia-foss/manual-connections) for manually connecting to PIA. The [get_region_and_token.sh](https://github.com/pia-foss/manual-connections/blob/master/get_region_and_token.sh) immediately caught my eye: what token?? When you check [how they use openvpn](https://github.com/pia-foss/manual-connections/blob/master/connect_to_openvpn_with_token.sh), you see [that token reused](https://github.com/pia-foss/manual-connections/blob/master/connect_to_openvpn_with_token.sh#L113).

I think this might be applicable when an account has enabled 2fa. In any case, I was finally able to get the container to work for me:

```sh
$ docker exec -it gluetun wget -qO- https://ipinfo.io
{
  "ip": "46.246.122.75",
  "city": "Märsta",
  "region": "Stockholm",
  "country": "SE",
  "loc": "59.6216,17.8548",
  "org": "AS42708 GleSYS AB",
  "postal": "195 00",
  "timezone": "Europe/Stockholm",
  "readme": "https://ipinfo.io/missingauth"
```

cc @qdm12 maybe that's something for wiki/readme/the nice log output that links to this issue
