### ISSUE TITLE
Bug: protonvpn port forwarding connection refused

### ISSUE THREAD

**Issue by UltraBlackLinux** [qdm12/gluetun#2679]
### Is this urgent?

No

### Host OS

Arch Linux

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

13532c8

### What's the problem 🤔

Port forwarding servers do not work despite having added +pmp to my openvpn username. Gluetun tries to connect but fails. I have confirmed several times that it is there and that I've regenerated my containers, to no avail.

Even though there's an IO timeout at the end of my logs, the proxy at least works completely fine.

### Share your logs (at least 10 lines)

```plain text
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [vpn] starting
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [firewall] allowing VPN connection...
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [openvpn] OpenVPN 2.6.11 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [openvpn] library versions: OpenSSL 3.3.2 3 Sep 2024, LZO 2.10
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]212.92.104.241:1194
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [openvpn] UDPv4 link local: (not bound)
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [openvpn] UDPv4 link remote: [AF_INET]212.92.104.241:1194
gluetun-vpn  | 2025-02-01T14:42:51Z INFO [openvpn] [node-nl-167.protonvpn.net] Peer Connection Initiated with [AF_INET]212.92.104.241:1194
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] setsockopt TCP_NODELAY=1 failed
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] TUN/TAP device tun0 opened
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] /sbin/ip link set dev tun0 up mtu 1500
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] /sbin/ip link set dev tun0 up
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] /sbin/ip addr add dev tun0 10.27.0.6/16
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] UID set to nonrootuser
gluetun-vpn  | 2025-02-01T14:42:52Z INFO [openvpn] Initialization Sequence Completed
gluetun-vpn  | 2025-02-01T14:42:53Z INFO [healthcheck] healthy!
gluetun-vpn  | 2025-02-01T14:42:54Z INFO [ip getter] Public IP address is 212.92.104.248 (Netherlands, North Brabant, Roosendaal - source: ipinfo)
gluetun-vpn  | 2025-02-01T14:42:54Z INFO [port forwarding] starting
gluetun-vpn  | 2025-02-01T14:42:54Z ERROR [vpn] starting port forwarding service: port forwarding for the first time: getting external IPv4 address: executing remote procedure call: reading from udp connection: read udp 10.27.0.6:54346->10.27.0.1:5351: recvfrom: connection refused - make sure you have +pmp at the end of your OpenVPN username
gluetun-vpn  | 2025-02-01T14:42:56Z WARN [dns] dialing tls server for request IN A cloudflare.com.: dial tcp 1.0.0.1:853: i/o timeout
```

### Share your configuration

```yml
gluetun-vpn:
        image: qmcgaw/gluetun
        container_name: gluetun-vpn
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        ports:
            - 8389:8888/tcp # HTTP proxy

            - 7575:7575 # QBT
            - 7676:7676 # QBT
            - 7676:7676/udp # QBT
            - 7777:9696 # PRLR
            - 7878:7878 # RDR
        volumes:
            - /podconf/vpn/gluetun:/gluetun
        environment:
            - HTTPPROXY=on
            - HTTPPROXY_USER=<>
            - HTTPPROXY_PASSWORD=<>
            - HTTPPROXY_LOG=on
            - HTTPPROXY_STEALTH=on

            # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/protonvpn.md
            - VPN_SERVICE_PROVIDER=protonvpn

            - SERVER_COUNTRIES=Germany,Poland,France,Denmark,Netherlands,Ireland,Austria
            - STREAM_ONLY=off
            - SECURE_CORE_ONLY=off

            # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/vpn-port-forwarding.md#qbittorrent-example
            - VPN_PORT_FORWARDING=on
            - PORT_FORWARD_ONLY=on
            - VPN_PORT_FORWARDING_UP_COMMAND=/bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:7575/api/v2/app/setPreferences 2>&1'
            - OPENVPN_USER=<>+pmp+nr
            - OPENVPN_PASSWORD=<>
```

**Comment by qdm12** [comment]
Are you sure vpn server `212.92.104.248` supports port forwarding? If you get `connection refused` it might be because there is no natpmp server listening on that server. 🤔

**Comment by UltraBlackLinux** [comment]
I sure hope it would. I'm letting gluetun choose the VPN server.
I thought that `PORT_FORWARD_ONLY=on` would ensure that the server supports port forwarding.

**Comment by mjtbrady** [comment]
Are you on a paid plan?  I do not believe that the free plan supports port forwarding.

**Comment by UltraBlackLinux** [comment]
I am on a paid plan, yes. I would expect gluetun to find zero servers at all if I was on the free plan.

**Comment by mjtbrady** [comment]
Gluetun doesn't know what plan you have.  It will only use the Free servers if you tell it to with `FREE_ONLY=on`.  You haven't set that, so I had to ask.

I am using ProtonVPN with port forwarding and it does work.

Here is what the log should look like when it works:
```
2025-02-08T15:05:18+13:00 INFO [openvpn] Initialization Sequence Completed
2025-02-08T15:05:18+13:00 INFO [dns] downloading hostnames and IP block lists
2025-02-08T15:05:20+13:00 INFO [healthcheck] healthy!
2025-02-08T15:05:22+13:00 INFO [dns] DNS server listening on [::]:53
2025-02-08T15:05:23+13:00 INFO [dns] ready
2025-02-08T15:05:26+13:00 INFO [ip getter] Public IP address is 77.247.178.147 (Netherlands, North Holland, Amsterdam - source: ipinfo)
2025-02-08T15:05:28+13:00 INFO [vpn] You are running 1 commit behind the most recent latest
2025-02-08T15:05:28+13:00 INFO [port forwarding] starting
2025-02-08T15:05:28+13:00 INFO [port forwarding] gateway external IPv4 address is 77.247.178.147
2025-02-08T15:05:29+13:00 INFO [port forwarding] port forwarded is 33261
2025-02-08T15:05:29+13:00 INFO [firewall] setting allowed input port 33261 through interface tun0...
2025-02-08T15:05:29+13:00 INFO [port forwarding] writing port file /tmp/gluetun/forwarded_port
2025-02-08T15:05:29+13:00 INFO [port forwarding] --2025-02-08 15:05:29--  http://127.0.0.1:8080/api/v2/app/setPreferences
2025-02-08T15:05:29+13:00 INFO [port forwarding] Connecting to 127.0.0.1:8080... connected.
2025-02-08T15:05:29+13:00 INFO [port forwarding] HTTP request sent, awaiting response... 200 OK
2025-02-08T15:05:29+13:00 INFO [port forwarding] Length: 0 [text/plain]
2025-02-08T15:05:29+13:00 INFO [port forwarding] Saving to: 'STDOUT'
2025-02-08T15:05:29+13:00 INFO [port forwarding] 
2025-02-08T15:05:29+13:00 INFO [port forwarding]      0K                                                        0.00 =0s
2025-02-08T15:05:29+13:00 INFO [port forwarding] 
2025-02-08T15:05:29+13:00 INFO [port forwarding] 2025-02-08 15:05:29 (0.00 B/s) - written to stdout [0/0]
2025-02-08T15:05:29+13:00 INFO [port forwarding]
```

Only thing I can suggest at this point is to add `LOG_LEVEL=debug` to the environment variables and see if that provides any  insight as to what is going on.

**Comment by UltraBlackLinux** [comment]
I was made aware that 3.31.1 works absolutely fine in terms of port forwarding, which I can confirm. Seems to be some kind of regression.

**Comment by izu-co** [comment]
For me, `+pmp` works just fine, but `+pmp+nr` does not.

**Comment by bgarnz** [comment]
Resurrecting thread to say I have the same problem. I'm using a paid account. It's wireguard, so there isn't anything for me to add +pmp to AFAIK (it's for openvpn, isn't it?). 

```
2025-11-13T03:24:19Z INFO [routing] default route found: interface eth0, gateway 172.18.0.1, assigned IP 172.18.0.2 and family v4

2025-11-13T03:24:19Z DEBUG [netlink] ip -4 rule list
2025-11-13T03:24:19Z DEBUG [netlink] ip -6 rule list
2025-11-13T03:24:19Z DEBUG [netlink] ip -f 0 rule add from 172.18.0.2/32 lookup 200 pref 100
2025-11-13T03:24:19Z INFO [routing] adding route for 0.0.0.0/0
2025-11-13T03:24:19Z DEBUG [routing] ip route replace 0.0.0.0/0 via 172.18.0.1 dev eth0 table 200
2025-11-13T03:24:19Z INFO [firewall] setting allowed subnets...
2025-11-13T03:24:19Z INFO [routing] default route found: interface eth0, gateway 172.18.0.1, assigned IP 172.18.0.2 and family v4
2025-11-13T03:24:19Z DEBUG [netlink] ip -4 rule list
2025-11-13T03:24:19Z DEBUG [netlink] ip -6 rule list
2025-11-13T03:24:19Z DEBUG [netlink] ip -f 0 rule add to 172.18.0.0/16 lookup 254 pref 98
2025-11-13T03:24:19Z INFO [dns] using plaintext DNS at address 10.2.0.1
2025-11-13T03:24:19Z INFO [healthcheck] listening on 127.0.0.1:9999
2025-11-13T03:24:19Z INFO [http server] http server listening on [::]:8000
2025-11-13T03:24:19Z DEBUG [wireguard] Wireguard server public key: RkAD/FzM/P0hJ7kCVUcbq9apozsgyoBTbCxhnR94+Ho=
2025-11-13T03:24:19Z DEBUG [wireguard] Wireguard client private key: EFm...WE=
2025-11-13T03:24:19Z DEBUG [wireguard] Wireguard pre-shared key: [not set]
2025-11-13T03:24:19Z INFO [firewall] allowing VPN connection...
2025-11-13T03:24:19Z DEBUG [firewall] /usr/sbin/iptables --append OUTPUT -d 74.118.126.108 -o eth0 -p udp -m udp --dport 51820 -j ACCEPT
2025-11-13T03:24:19Z DEBUG [firewall] /usr/sbin/iptables --append OUTPUT -o tun0 -j ACCEPT
2025-11-13T03:24:19Z DEBUG [firewall] /usr/sbin/ip6tables --append OUTPUT -o tun0 -j ACCEPT
2025-11-13T03:24:19Z INFO [wireguard] Using available kernelspace implementation
2025-11-13T03:24:19Z INFO [wireguard] Connecting to 74.118.126.108:51820
2025-11-13T03:24:19Z DEBUG [netlink] ip -f inet rule add lookup 51820 pref 101
2025-11-13T03:24:19Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2025-11-13T03:24:24Z INFO [dns] downloading hostnames and IP block lists
2025-11-13T03:24:27Z INFO [dns] DNS server listening on [::]:53
2025-11-13T03:24:27Z INFO [dns] ready
2025-11-13T03:24:28Z INFO [ip getter] Public IP address is 74.118.126.111 (United Kingdom, England, Beckenham - source: ipinfo)
2025-11-13T03:24:29Z INFO [vpn] You are running on the bleeding edge of latest!
2025-11-13T03:24:29Z INFO [port forwarding] starting
2025-11-13T03:24:29Z ERROR [vpn] starting port forwarding service: port forwarding for the first time: getting external IPv4 address: executing remote procedure call: reading from udp connection: read udp 10.2.0.2:49308->10.2.0.1:5351: recvfrom: connection refused - make sure you have +pmp at the end of your OpenVPN username
```

**Comment by scraunt** [comment]
@bgarnz 

I've been hunting down a similar issue recently, I actually just got port forwarding working again right after reading your comment. 

What I did: 
- Generated a new ProtonVPN wireguard config from https://account.protonvpn.com, and ensured port forwarding was selected (it defaults to off, which I think may have been my problem), then click 'create' in the server region you are currently using for `- SERVER_COUNTRIES=`. I also gave the generated config a name, and commented that name accordingly in my compose file. 
- I am using the image `qmcgaw/gluetun:pr-2586` - I was using this as part of my troubleshooting process and have not yet changed back to the latest tag. I'm curious what image you are using. 

This is just what I did, so not everything may have been necessary. 

Good luck!

**Comment by bgarnz** [comment]
@scraunt Thanks for the direction, I may have missed that toggle. I've now made sure I hit it, and instead I'm getting a different error:
`ERROR [vpn] finding a VPN server: filtering servers: no server found: for VPN wireguard; protocol udp; country netherlands; encryption preset normal; port forwarding only; secure core only; target ip address 0.0.0.0` 

Not sure if I'm supposed to be specifying an IP address, I don't see that mentioned in any wiki pages.

**Comment by scraunt** [comment]
@bgarnz 

I have not encountered that error, but you may need you capitalize netherlands, my country line in my compose: 
```
          - SERVER_COUNTRIES=Netherlands
```


I also have set: 
```
          - VPN_SERVICE_PROVIDER=protonvpn
          - VPN_TYPE=wireguard
```


If you're still having trouble paste a bit more of your log and your run command or compose file. Perhaps best in a new issue if this is now unrelated to port forwarding. Feel free to tag me.

**Comment by bgarnz** [comment]
@scraunt I've already set those, unfortunately. It definitely has to do with port forwarding, that's the thing that's not working here.



Here's my run:
```
docker run

  -d
  --name='GluetunVPN'
  --net='dockernet'
  --pids-limit 2048
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="~~~~~~~~~"
  -e HOST_CONTAINERNAME="GluetunVPN"
  -e 'VPN_SERVICE_PROVIDER'='protonvpn'
  -e 'VPN_TYPE'='wireguard'
  -e 'PRIVATE_INTERNET_ACCESS_OPENVPN_ENCRYPTION_PRESET'='normal'
  -e 'OPENVPN_USER'=''
  -e 'OPENVPN_PASSWORD'=''
  -e 'OPENVPN_PROTOCOL'='udp'
  -e 'WIREGUARD_PRIVATE_KEY'='~~~~~~~~~~~~~~~~~~~~~~~~~~'
  -e 'WIREGUARD_ADDRESSES'='10.2.0.2/32'
  -e 'SERVER_COUNTRIES'=''
  -e 'SERVER_REGIONS'=''
  -e 'SERVER_CITIES'=''
  -e 'SERVER_HOSTNAMES'=''
  -e 'SERVER_NAMES'=''
  -e 'SERVER_CATEGORIES'=''
  -e 'VPN_PORT_FORWARDING'='on'
  -e 'FIREWALL_VPN_INPUT_PORTS'=''
  -e 'FIREWALL_INPUT_PORTS'=''
  -e 'FIREWALL_OUTBOUND_SUBNETS'=''
  -e 'DOT'='on'
  -e 'DOT_PROVIDERS'='cloudflare'
  -e 'BLOCK_MALICIOUS'='on'
  -e 'BLOCK_SURVEILLANCE'='off'
  -e 'BLOCK_ADS'='off'
  -e 'HTTPPROXY'='off'
  -e 'SHADOWSOCKS'='off'
  -e 'SHADOWSOCKS_PASSWORD'=''
  -e 'TZ'='America/New_York'
  -e 'SECURE_CORE_ONLY'='on'
  -e 'PORT_FORWARD_ONLY'='on'
  -e 'UPDATER_PROTONVPN_USERNAME'='~~~~~~~~~~~~~~~~~~~~~~~'
  -e 'UPDATER_PROTONVPN_PASSWORD'='~~~~~~~~~~~~~~~~'
  -e 'VPN_INTERFACE'='tun0'
  -e 'OPENVPN_VERSION'='2.6'
  -e 'OPENVPN_ENDPOINT_IP'=''
  -e 'OPENVPN_ENDPOINT_PORT'=''
  -e 'OPENVPN_VERBOSITY'='1'
  -e 'OPENVPN_FLAGS'=''
  -e 'OPENVPN_ROOT'='no'
  -e 'OPENVPN_CIPHERS'=''
  -e 'OPENVPN_AUTH'=''
  -e 'OPENVPN_MSSFIX'='0'
  -e 'OPENVPN_CUSTOM_CONFIG'=''
  -e 'WIREGUARD_PUBLIC_KEY'=''
  -e 'WIREGUARD_ENDPOINT_IP'=''
  -e 'WIREGUARD_ENDPOINT_PORT'=''
  -e 'WIREGUARD_PRESHARED_KEY'=''
  -e 'WIREGUARD_ALLOWED_IPS'='0.0.0.0/0,::/0'
  -e 'WIREGUARD_IMPLEMENTATION'='auto'
  -e 'WIREGUARD_MTU'='1400'
  -e 'WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL'=''
  -e 'VPN_PORT_FORWARDING_PROVIDER'='protonvpn'
  -e 'VPN_PORT_FORWARDING_STATUS_FILE'='/gluetun/forwarded_port'
  -e 'VPN_PORT_FORWARDING_LISTENING_PORT'=''
  -e 'FIREWALL_DEBUG'='off'
  -e 'DOT_CACHING'='on'
  -e 'DOT_PRIVATE_ADDRESS'='127.0.0.1/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16,::1/128,fc00::/7,fe80::/10,::ffff:7f00:1/104,::ffff:a00:0/104,::ffff:a9fe:0/112,::ffff:ac10:0/108,::ffff:c0a8:0/112'
  -e 'DOT_IPV6'='off'
  -e 'DNS_UPDATE_PERIOD'='24h'
  -e 'UNBLOCK'=''
  -e 'DNS_ADDRESS'='10.2.0.1'
  -e 'DNS_KEEP_NAMESERVER'='off'
  -e 'HTTPPROXY_LOG'='off'
  -e 'HTTPPROXY_LISTENING_ADDRESS'=':8888'
  -e 'HTTPPROXY_USER'=''
  -e 'HTTPPROXY_PASSWORD'=''
  -e 'HTTPPROXY_STEALTH'='off'
  -e 'SHADOWSOCKS_LOG'='off'
  -e 'SHADOWSOCKS_LISTENING_ADDRESS'=':8388'
  -e 'SHADOWSOCKS_CIPHER'='chacha20-ietf-poly1305'
  -e 'HTTP_CONTROL_SERVER_ADDRESS'=':8000'
  -e 'HTTP_CONTROL_SERVER_LOG'='on'
  -e 'HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH'=''
  -e 'HEALTH_TARGET_ADDRESS'='cloudflare.com:443'
  -e 'HEALTH_VPN_DURATION_INITIAL'='6s'
  -e 'HEALTH_VPN_DURATION_ADDITION'='5s'
  -e 'HEALTH_SUCCESS_WAIT_DURATION'='5s'
  -e 'HEALTH_SERVER_ADDRESS'='127.0.0.1:9999'
  -e 'UPDATER_PERIOD'='24h'
  -e 'UPDATER_MIN_RATIO'='0.8'
  -e 'UPDATER_VPN_SERVICE_PROVIDERS'=''
  -e 'STORAGE_FILEPATH'='/gluetun/servers.json'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'PUBLICIP_ENABLED'='true'
  -e 'PUBLICIP_API'='ipinfo'
  -e 'PUBLICIP_API_TOKEN'=''
  -e 'PUBLICIP_FILE'='/gluetun/ip'
  -e 'VERSION_INFORMATION'='on'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/binhex/docker-templates/master/binhex/images/gluetun-icon.png'
  -p '8000:8000/tcp'
  -p '8888:8888/tcp'
  -p '8388:8388/tcp'
  -p '8388:8388/udp'
  -v '/mnt/cache/appdata/gluetun':'/gluetun':'rw'
  --cap-add=NET_ADMIN
  --device /dev/net/tun:/dev/net/tun 'qmcgaw/gluetun'
f373ef8ed1a841bafb2ba4513cb364b1d86607142470c63d9633c20edc2b839f
```

**Comment by scraunt** [comment]
<del>@bgarnz  I am now getting the same error (no servers available) after pulling the latest image, it's unfortunate that Netherlands is uncapitalised in the logs, as it creates a wild goose chase as we have experienced here. For now I will run an older image. It's worth noting to the maintainers (Quentin) that I am using a throwaway free tier account (as suggested) for the updater. Port forwarding is not available for the free accounts, so I would be interested to try a paid account for the updater run, and see if this makes a difference (would be understandable if the free tier account's could not return info on paid servers). </del>

@bgarnz 

Not sure which of the below fixed it

I manually ran `docker run -it --rm -v /data/docker/qbt-gluetun/gluetun:/gluetun qmcgaw/gluetun:latest update -enduser -providers protonvpn -proton-password <PASSWORD> -proton-username <USERNAME>` with my paid account credentials. 

<del>I then in my compose file changed to tag 3.40.1</del> - changed back to the latest tag in my compose and the error remains gone. 

And now the error went away and my forwarded port is returned in the logs. 


@qdm12 

Do you have a paid proton account to test? Let me know I can probably help you out with one temporarily if it would assist in hunting down a fix for this, and thank you for your continued work on the project.

**Comment by qdm12** [comment]
#2985 is fixed just now, so paid servers data should be back on the menu

**Comment by qdm12** [comment]
Is this fixed?

Running protonvpn + port forwarding with a paid account and wireguard works fine over here, at least on the latest image.

Does v3.40.3 work for you?

Note I'll close this due to inactivity in 24hrs if no comment (this blocks next release)

**Comment by qdm12** [comment]
Closing due to inactivity, please re-open an issue if you're still facing issues

**Comment by gregwalters** [comment]
Sorry for the late response... had an offline weekend. Yes, still happening on the latest release. I've a paid membership and specified port forwarding when creating my config. Looks like I don't have permission to re-open this.

```Running version v3.40.3 built on 2025-11-18T21:59:50.593Z (commit 01e9274)

🔧 Need help? ☕ Discussion? https://github.com/qdm12/gluetun/discussions/new/choose
🐛 Bug? ✨ New feature? https://github.com/qdm12/gluetun/issues/new/choose
💻 Email? quentin.mcgaw@gmail.com
💰 Help me? https://www.paypal.me/qmcgaw https://github.com/sponsors/qdm12
2025-11-24T14:17:27Z INFO [routing] default route found: interface eth0, gateway SNIP, assigned IP SNIP and family v4
2025-11-24T14:17:27Z INFO [routing] default route found: interface eth0, gateway SNIP, assigned IP SNIP and family v6
2025-11-24T14:17:27Z INFO [routing] local ethernet link found: eth0
2025-11-24T14:17:27Z INFO [routing] local ipnet found: SNIP/32
2025-11-24T14:17:27Z INFO [routing] local ipnet found: SNIP/128
2025-11-24T14:17:27Z INFO [routing] local ipnet found: SNIP/128
2025-11-24T14:17:27Z INFO [routing] local ipnet found: SNIP::/64
2025-11-24T14:17:27Z INFO [firewall] enabling...
2025-11-24T14:17:27Z DEBUG [firewall] /sbin/iptables --policy INPUT DROP
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --policy OUTPUT DROP
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --policy FORWARD DROP
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --policy INPUT DROP
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --policy OUTPUT DROP
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --policy FORWARD DROP
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --append INPUT -i lo -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append INPUT -i lo -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --append OUTPUT -o lo -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append OUTPUT -o lo -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --append OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --append INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --append OUTPUT -o eth0 -s SNIP -d SNIP/32 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append OUTPUT -o eth0 -d SNIP/104 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append OUTPUT -o eth0 -s SNIP -d SNIP/128 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append OUTPUT -o eth0 -s SNIP -d SNIP/128 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append OUTPUT -o eth0 -s SNIP -d SNIP/64 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --append INPUT -i eth0 -d SNIP/32 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append INPUT -i eth0 -d SNIP/128 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append INPUT -i eth0 -d SNIP/128 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append INPUT -i eth0 -d SNIP/64 -j ACCEPT
2025-11-24T14:17:28Z INFO [firewall] enabled successfully
2025-11-24T14:17:28Z INFO [storage] creating /gluetun/servers.json with 21098 hardcoded servers
2025-11-24T14:17:28Z DEBUG [netlink] IPv6 is supported by link eth0
2025-11-24T14:17:28Z INFO Alpine version: 3.20.8
2025-11-24T14:17:28Z INFO OpenVPN 2.5 version: 2.5.10
2025-11-24T14:17:28Z INFO OpenVPN 2.6 version: 2.6.11
2025-11-24T14:17:28Z INFO IPtables version: v1.8.10
2025-11-24T14:17:28Z INFO Settings summary:
├── VPN settings:
|   ├── VPN provider settings:
|   |   ├── Name: protonvpn
|   |   ├── Server selection settings:
|   |   |   ├── VPN type: wireguard
|   |   |   ├── Countries: canada
|   |   |   ├── Cities: toronto
|   |   |   ├── Port forwarding only servers: yes
|   |   |   └── Wireguard selection settings:
|   |   └── Automatic port forwarding settings:
|   |       ├── Redirection listening port: disabled
|   |       ├── Use port forwarding code for current provider
|   |       ├── Forwarded port file path: /tmp/gluetun/forwarded_port
|   |       └── Forwarded port up command: /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://127.0.0.1:8080/api/v2/app/setPreferences 2>&1'
|   └── Wireguard settings:
|       ├── Private key: SNIP
|       ├── Interface addresses:
|       |   └── SNIP/32
|       ├── Allowed IPs:
|       |   ├── 0.0.0.0/0
|       |   └── ::/0
|       └── Network interface: tun0
|           └── MTU: 1320
├── DNS settings:
|   ├── Keep existing nameserver(s): no
|   ├── DNS server address to use: 127.0.0.1
|   └── DNS over TLS settings:
|       ├── Enabled: yes
|       ├── Update period: every 24h0m0s
|       ├── Upstream resolvers:
|       |   └── cloudflare
|       ├── Caching: yes
|       ├── IPv6: no
|       └── DNS filtering settings:
|           ├── Block malicious: yes
|           ├── Block ads: no
|           ├── Block surveillance: no
|           └── Blocked IP networks:
|               ├── 127.0.0.1/8
|               ├── 10.0.0.0/8
|               ├── 172.16.0.0/12
|               ├── 192.168.0.0/16
|               ├── 169.254.0.0/16
|               ├── ::1/128
|               ├── fc00::/7
|               ├── fe80::/10
|               ├── ::ffff:127.0.0.1/104
|               ├── ::ffff:10.0.0.0/104
|               ├── ::ffff:169.254.0.0/112
|               ├── ::ffff:172.16.0.0/108
|               └── ::ffff:192.168.0.0/112
├── Firewall settings:
|   ├── Enabled: yes
|   ├── Input ports:
|   |   └── 8080
|   └── Outbound subnets:
|       ├── SNIP/23
|       └── SNIP/8
├── Log settings:
|   └── Log level: debug
├── Health settings:
|   ├── Server listening address: 127.0.0.1:9999
|   ├── Target address: cloudflare.com:443
|   ├── Duration to wait after success: 5s
|   ├── Read header timeout: 100ms
|   ├── Read timeout: 500ms
|   └── VPN wait durations:
|       ├── Initial duration: 6s
|       └── Additional duration: 5s
├── Shadowsocks server settings:
|   └── Enabled: no
├── HTTP proxy settings:
|   └── Enabled: no
├── Control server settings:
|   ├── Listening address: :8000
|   ├── Logging: yes
|   └── Authentication file path: /gluetun/auth/config.toml
├── Storage settings:
|   └── Filepath: /gluetun/servers.json
├── OS Alpine settings:
|   ├── Process UID: 1000
|   ├── Process GID: 1000
|   └── Timezone: etc/utc
├── Public IP settings:
|   ├── IP file path: /tmp/gluetun/ip
|   ├── Public IP data base API: ipinfo
|   └── Public IP data backup APIs:
|       ├── ifconfigco
|       ├── ip2location
|       └── cloudflare
└── Version settings:
    └── Enabled: yes
2025-11-24T14:17:28Z INFO [routing] default route found: interface eth0, gateway SNIP, assigned IP SNIP and family v4
2025-11-24T14:17:28Z INFO [routing] default route found: interface eth0, gateway SNIP, assigned IP SNIP and family v6
2025-11-24T14:17:28Z DEBUG [netlink] ip -4 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -6 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -f 0 rule add from SNIP/32 lookup 200 pref 100
2025-11-24T14:17:28Z DEBUG [netlink] ip -4 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -6 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -f 0 rule add from SNIP/128 lookup 200 pref 100
2025-11-24T14:17:28Z INFO [routing] adding route for 0.0.0.0/0
2025-11-24T14:17:28Z DEBUG [routing] ip route replace 0.0.0.0/0 via SNIP dev eth0 table 200
2025-11-24T14:17:28Z INFO [routing] adding route for ::/0
2025-11-24T14:17:28Z DEBUG [routing] ip route replace ::/0 via SNIP dev eth0 table 200
2025-11-24T14:17:28Z INFO [firewall] setting allowed subnets...
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --append OUTPUT -o eth0 -s SNIP -d SNIP/23 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --append OUTPUT -o eth0 -s SNIP -d SNIP/8 -j ACCEPT
2025-11-24T14:17:28Z INFO [routing] default route found: interface eth0, gateway SNIP, assigned IP SNIP and family v4
2025-11-24T14:17:28Z INFO [routing] default route found: interface eth0, gateway SNIP, assigned IP SNIP and family v6
2025-11-24T14:17:28Z INFO [routing] adding route for SNIP/23
2025-11-24T14:17:28Z DEBUG [routing] ip route replace SNIP/23 via SNIP dev eth0 table 199
2025-11-24T14:17:28Z DEBUG [netlink] ip -4 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -6 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -f 0 rule add to SNIP23 lookup 199 pref 99
2025-11-24T14:17:28Z INFO [routing] adding route for SNIP/8
2025-11-24T14:17:28Z DEBUG [routing] ip route replace SNIP/8 via SNIP dev eth0 table 199
2025-11-24T14:17:28Z DEBUG [netlink] ip -4 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -6 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -f 0 rule add to SNIP/8 lookup 199 pref 99
2025-11-24T14:17:28Z DEBUG [netlink] ip -4 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -6 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -f 0 rule add to SNIP/32 lookup 254 pref 98
2025-11-24T14:17:28Z DEBUG [netlink] ip -4 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -6 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -f 0 rule add to SNIP/128 lookup 254 pref 98
2025-11-24T14:17:28Z DEBUG [netlink] ip -4 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -6 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -f 0 rule add to SNIP/128 lookup 254 pref 98
2025-11-24T14:17:28Z DEBUG [netlink] ip -4 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -6 rule list
2025-11-24T14:17:28Z DEBUG [netlink] ip -f 0 rule add to SNIP::/64 lookup 254 pref 98
2025-11-24T14:17:28Z INFO [firewall] setting allowed input port 8080 through interface eth0...
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --append INPUT -i eth0 -p tcp -m tcp --dport 8080 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append INPUT -i eth0 -p tcp -m tcp --dport 8080 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --append INPUT -i eth0 -p udp -m udp --dport 8080 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append INPUT -i eth0 -p udp -m udp --dport 8080 -j ACCEPT
2025-11-24T14:17:28Z INFO [dns] using plaintext DNS at address 1.1.1.1
2025-11-24T14:17:28Z INFO [http server] http server listening on [::]:8000
2025-11-24T14:17:28Z DEBUG [wireguard] Wireguard server public key: QPfiwJQmt5VLEOh1ufLbi1lj6LUnwQY0tgDSh3pWx1k=
2025-11-24T14:17:28Z DEBUG [wireguard] Wireguard client private key: SNIP
2025-11-24T14:17:28Z DEBUG [wireguard] Wireguard pre-shared key: [not set]
2025-11-24T14:17:28Z INFO [firewall] allowing VPN connection...
2025-11-24T14:17:28Z INFO [healthcheck] listening on 127.0.0.1:9999
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --append OUTPUT -d 185.111.110.1 -o eth0 -p udp -m udp --dport 51820 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --append OUTPUT -d 185.111.110.1 -o eth0 -p udp -m udp --dport 51820 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/iptables --append OUTPUT -o tun0 -j ACCEPT
2025-11-24T14:17:28Z DEBUG [firewall] /sbin/ip6tables --append OUTPUT -o tun0 -j ACCEPT
2025-11-24T14:17:28Z INFO [wireguard] Using available kernelspace implementation
2025-11-24T14:17:28Z INFO [wireguard] Connecting to 185.111.110.1:51820
2025-11-24T14:17:28Z DEBUG [netlink] ip -f inet6 rule add lookup 51820 pref 101
2025-11-24T14:17:28Z DEBUG [netlink] ip -f inet rule add lookup 51820 pref 101
2025-11-24T14:17:28Z INFO [wireguard] Wireguard setup is complete. Note Wireguard is a silent protocol and it may or may not work, without giving any error message. Typically i/o timeout errors indicate the Wireguard connection is not working.
2025-11-24T14:17:28Z INFO [dns] downloading hostnames and IP block lists
2025-11-24T14:17:33Z INFO [healthcheck] healthy!
2025-11-24T14:17:34Z INFO [dns] DNS server listening on [::]:53
2025-11-24T14:17:35Z INFO [dns] ready
2025-11-24T14:17:35Z INFO [ip getter] Public IP address is 185.98.171.54 (Canada, Ontario, Toronto - source: ipinfo)
2025-11-24T14:17:35Z INFO [vpn] You are running the latest release v3.40.3
2025-11-24T14:17:35Z INFO [port forwarding] starting
2025-11-24T14:19:43Z ERROR [vpn] starting port forwarding service: port forwarding for the first time: getting external IPv4 address: executing remote procedure call: connection timeout: failed attempts: read udp SNIP:40302->SNIP:5351: i/o timeout (tries 1, 2, 3, 4, 5, 6, 7, 8, 9)```

**Comment by brunoorsolon** [comment]
Hey I was having the same issue after switching to ProtonVPN
It's very frustrating because I would """fix"""" it and a few hours later it would break again. It drove me crazy for a few weeks.

I got tired of all the workarounds that never worked and wrote a script to just sync the damn thing and restart the services when it can't. I will leave a link here, it's simple and doesn't do anything it shouldn't but as with any code on the internet, make sure to read it before you run ;) 

https://github.com/brunoorsolon/gluetun-qbt-watchdog

PS.: My personal setup is Gluetun + ProtonVPN (WireGuard) + qbittorrent. I can say it works for this specific case but can't really confirm it will fix any other combinations. Feel free to experiment and fork it if you need to solve a slightly different problem or send a PR if it can be integrated with the current one. I hope it helps someone out there.

**Comment by EricMyhrer** [comment]
> Hey I was having the same issue after switching to ProtonVPN It's very frustrating because I would """fix"""" it and a few hours later it would break again. It drove me crazy for a few weeks.
> 
> I got tired of all the workarounds that never worked and wrote a script to just sync the damn thing and restart the services when it can't. I will leave a link here, it's simple and doesn't do anything it shouldn't but as with any code on the internet, make sure to read it before you run ;)
> 
> https://github.com/brunoorsolon/gluetun-qbt-watchdog
> 
> PS.: My personal setup is Gluetun + ProtonVPN (WireGuard) + qbittorrent. I can say it works for this specific case but can't really confirm it will fix any other combinations. Feel free to experiment and fork it if you need to solve a slightly different problem or send a PR if it can be integrated with the current one. I hope it helps someone out there.

Thank you so much. I had spent countless hours having issues, read documentation upon documentation, tried various work arounds, and was about to just write my own script. This is phenomenal and works like a charm. Cheers.

**Comment by qdm12** [comment]
you can use the gluetun port forwarding up and down commands to update qbittorrent's port, see the wiki there is an example exactly for that

**Comment by EricMyhrer** [comment]
> you can use the gluetun port forwarding up and down commands to update qbittorrent's port, see the wiki there is an example exactly for that

I am aware, I’ve read and implemented that doc many times. It is not stable for whatever reason. I use the same stack as Bruno and across all solutions that I have tried and tried again, his watchdog was the first one to maintain stability for an extended period.
