### ISSUE TITLE
Bug: Cant update server list

### ISSUE THREAD

**Issue by soejoc** [qdm12/gluetun#2961]
### Is this urgent?

No

### Host OS

Debian GNU/Linux 13 (trixie)

### CPU arch

aarch64

### VPN service provider

Cyberghost

### What are you using to run the container

docker run

### What is the version of Gluetun

Running version latest built on 2025-10-30T16:18:16.881Z (commit 65f49ea)

### What's the problem 🤔

I run the following command accordingly to the docs to update the IPs of the Cyberghost servers:

```
docker run --rm -v ./gluetun:/gluetun qmcgaw/gluetun update -enduser -providers cyberghost

```

It finds no servers and uses the old, hardcoded ones, which are not up-to-date anymore (Maybe it can't resolve the domains of the servers?). Currently, I have to manually update the servers.json to connect to my VPN server. I have also tried to specify an explicit DNS server, which didn't work. I also tried to update the providers purevpn, airvpn and mullvad which worked. So it seems to be a problem related to cyberghost.

I tried to reproduce the behavior on another machine (x86_64, Ubuntu 22.04.5 LTS). There I could update the cyberghost servers.

### Share your logs (at least 10 lines)

```plain text
2025-11-01T16:24:25Z INFO creating /gluetun/servers.json with 20777 hardcoded servers
2025-11-01T16:24:25Z INFO updating Cyberghost servers...
2025-11-01T16:24:46Z WARN note: if running the update manually, you can use the flag -minratio to allow the update to succeed with less servers found
2025-11-01T16:24:46Z ERROR updating server information: getting servers: not enough servers found: 0 and expected at least 151
2025-11-01T16:24:46Z INFO Shutdown successful
```

### Share your configuration

```yml

```

**Comment by qdm12** [comment]
What are the current Cyberghost VPN server hostnames looking like?
Right now Gluetun does some kind of ugly bruteforcing ([code](https://github.com/qdm12/gluetun/blob/6712adfe6b72208815ac099e987702e6efabfa58/internal/provider/cyberghost/updater/hosttoserver.go#L13)) to have a list of all possible server hostnames given a list of [group ids](https://github.com/qdm12/gluetun/blob/6712adfe6b72208815ac099e987702e6efabfa58/internal/provider/cyberghost/updater/constants.go#L7) and [country codes](https://github.com/qdm12/gluetun/blob/6712adfe6b72208815ac099e987702e6efabfa58/internal/provider/cyberghost/updater/constants.go#L18) and then assemble them as `groupid-countrycode.cg-dialup.net`. Maybe that changed?

**Comment by qdm12** [comment]
Actually I just ran the updater just fine locally, and got 150 servers back. New servers pushed for the latest image with 7fbc5c3c07f52cdc43af26f3c16664909dc6e096

However, digging a bit, I noticed Cyberghost did not have its DNS lookup warnings logged, this is fixed in 43da9ddbb3a0a95b731b8b38661ec172643d7387 - can you try re-running the updater to see what errors you get logged as warnings?

**Comment by soejoc** [comment]
The format of the hostnames is still the same. I just ran the same command with the new image. These are the warning I get now:

```plain text
docker run --rm -v ./gluetun:/gluetun qmcgaw/gluetun update -enduser -providers cyberghost
2025-11-09T12:39:08Z INFO merging by most recent 20738 hardcoded servers and 20802 servers read from /gluetun/servers.json
2025-11-09T12:39:08Z INFO Using airvpn servers from file which are 463 days more recent
2025-11-09T12:39:08Z INFO Using mullvad servers from file which are 29 days more recent
2025-11-09T12:39:08Z INFO Using privatevpn servers from file which are 1250 days more recent
2025-11-09T12:39:08Z INFO Using purevpn servers from file which are 688 days more recent
2025-11-09T12:39:08Z INFO updating Cyberghost servers...
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-19-cv.cg-dialup.net: lookup 97-19-cv.cg-dialup.net on 100.100.100.100:53: read udp 172.17.0.2:50393->8.8.8.8:53: read: no route to host
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-19-mv.cg-dialup.net: lookup 97-19-mv.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-8-cv.cg-dialup.net: lookup 87-8-cv.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-1-bh.cg-dialup.net: lookup 97-1-bh.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-19-ru.cg-dialup.net: lookup 97-19-ru.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-19-in.cg-dialup.net: lookup 87-19-in.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-19-zw.cg-dialup.net: lookup 87-19-zw.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-19-tm.cg-dialup.net: lookup 87-19-tm.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-1-pn.cg-dialup.net: lookup 97-1-pn.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-8-ck.cg-dialup.net: lookup 97-8-ck.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-19-tv.cg-dialup.net: lookup 97-19-tv.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-19-gf.cg-dialup.net: lookup 97-19-gf.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-8-vg.cg-dialup.net: lookup 87-8-vg.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-19-ls.cg-dialup.net: lookup 87-19-ls.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-8-la.cg-dialup.net: lookup 87-8-la.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-8-nu.cg-dialup.net: lookup 97-8-nu.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-19-gf.cg-dialup.net: lookup 87-19-gf.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-8-ss.cg-dialup.net: lookup 97-8-ss.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-1-kn.cg-dialup.net: lookup 97-1-kn.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-19-et.cg-dialup.net: lookup 87-19-et.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-8-tg.cg-dialup.net: lookup 87-8-tg.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-8-mx.cg-dialup.net: lookup 97-8-mx.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-19-cd.cg-dialup.net: lookup 97-19-cd.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-8-cy.cg-dialup.net: lookup 87-8-cy.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-8-tm.cg-dialup.net: lookup 97-8-tm.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-19-nf.cg-dialup.net: lookup 87-19-nf.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-1-cm.cg-dialup.net: lookup 97-1-cm.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-19-sh.cg-dialup.net: lookup 97-19-sh.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-1-de.cg-dialup.net: lookup 87-1-de.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-19-tg.cg-dialup.net: lookup 97-19-tg.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-8-lc.cg-dialup.net: lookup 87-8-lc.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-8-fm.cg-dialup.net: lookup 87-8-fm.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-19-ua.cg-dialup.net: lookup 87-19-ua.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-1-rw.cg-dialup.net: lookup 87-1-rw.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-19-ir.cg-dialup.net: lookup 97-19-ir.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-19-gq.cg-dialup.net: lookup 97-19-gq.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-19-mt.cg-dialup.net: lookup 87-19-mt.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-1-sj.cg-dialup.net: lookup 97-1-sj.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-1-bw.cg-dialup.net: lookup 87-1-bw.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-8-br.cg-dialup.net: lookup 97-8-br.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-1-aw.cg-dialup.net: lookup 87-1-aw.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-8-is.cg-dialup.net: lookup 87-8-is.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-8-ee.cg-dialup.net: lookup 87-8-ee.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-1-uy.cg-dialup.net: lookup 97-1-uy.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-19-hk.cg-dialup.net: lookup 97-19-hk.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-1-ch.cg-dialup.net: lookup 87-1-ch.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-1-gn.cg-dialup.net: lookup 87-1-gn.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-8-gd.cg-dialup.net: lookup 97-8-gd.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-19-rs.cg-dialup.net: lookup 97-19-rs.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-8-to.cg-dialup.net: lookup 97-8-to.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-8-sh.cg-dialup.net: lookup 97-8-sh.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-8-md.cg-dialup.net: lookup 97-8-md.cg-dialup.net: i/o timeout
[...]
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-19-pm.cg-dialup.net: lookup 87-19-pm.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-1-lr.cg-dialup.net: lookup 87-1-lr.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 87-8-il.cg-dialup.net: lookup 87-8-il.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN reached the maximum number of consecutive failures: 10 failed attempts resolving 97-1-gy.cg-dialup.net: lookup 97-1-gy.cg-dialup.net: i/o timeout
2025-11-09T12:39:28Z WARN note: if running the update manually, you can use the flag -minratio to allow the update to succeed with less servers found
2025-11-09T12:39:28Z ERROR updating server information: getting servers: not enough servers found: 0 and expected at least 120
2025-11-09T12:39:28Z INFO Shutdown successful
```



So somehow gluetun is not able to resolve the hostnames. The hostname `87-1-de.cg-dialup.net` which is important for me is part of the list. I can resolve the hostname out of my docker container. I tested some other hostnames from the logs. Most of them actually don't seem to exist. So maybe there is a problem when gluetun tries to resolve a hole bunch of hostnames that don't exist, before it tries to resolve a valid hostname? Maybe it would also be a great idea to just resolve a specified list of hostnames with the update tool and not all hostnames of one provider. For me one specific hostname is enough.

**Comment by qdm12** [comment]
You have a DNS issue on your host, for example `100.100.100.100:53`?? `read: no route to host` 🤔 
Anyway, it's up to date in the latest image, so closing this, and can't reproduce this bug.
