### ISSUE TITLE
CyberGhost VPN doesn't work anymore

### ISSUE THREAD

**Issue by VMax2** [qdm12/gluetun#551]
**Is this urgent?**: yes

**Host OS** (approximate answer is fine too): Debian 10

**CPU arch** or **device name**: amd64

**What VPN provider are you using**: CyberGhost

**What are you using to run your container?**: Docker runPortainer

**What is the version of the program** (See the line at the top of your logs)

```
Running version latest built on 2021-07-29T13:54:44Z (commit 83c4ad2)

```

**What's the problem** 🤔

OpenVPN doesn't connect to CyberGhost's servers

**Share your logs... (careful to remove in example tokens)**

```log
2021/07/31 11:02:47 WARN TUN device is not available: open /dev/net/tun: no such file or directory
2021/07/31 11:02:47 ERROR openvpn: --explicit-exit-notify can only be used with --proto udp
2021/07/31 11:02:47 ERROR openvpn: exit status 1
2021/07/31 11:02:53 INFO healthcheck: program has been unhealthy for 6s: restarting OpenVPN
2021/07/31 11:03:40 ERROR shadowsocks: cannot connect to target address 0.0.0.0:53: dial tcp 0.0.0.0:53: connect: connection refused
```

This happen if i use TCP protocol, if i use UDP then i find in logs that no servers are available with that protocol

**Comment by VMax2** [comment]
Yesterday i updated the image from Portainer, before i did it everything was working realy fine

**Comment by qdm12** [comment]
- TCP bad openvpn option `explicit-exit-notify` is fixed in c17b351efbbfe95010f9657791b342befc54c9dc (error from your logs)
- UDP servers filtering should be fixed in 982536e9e831aae152f5fbdb587dafff9c6de0c9
Note that before gluetun would only take `CYBERGHOST_GROUP` into account and not `OPENVPN_PROTOCOL`.
Now it will complain you need to change the `CYBERGHOST_GROUP` to match the protocol, if you set the group. By default it will now use all UDP groups, unless you specify `OPENVPN_PROTOCOL=tcp` where it will use all TCP groups. You can still precise which groups you want, but they will have to match the `OPENVPN_PROTOCOL`.

Feel free to comment here if this is still unresolved.

**Comment by VMax2** [comment]
Thank you so much for all your great work, well, after several checks actual situation is that for tcp protocol everithing has reverted back to the previous situation and all work great, not the same is  for the udp one, it still doesn't work, it look like the italian hostname (wich is 87-1-it.cg-dialup.net) is missing into the udp group list, below i leave the log messages:

**(note, following logs are generated if i don't specify the server hostname but into the env section i specify only the protocol udp and the CyberGhost Group premium UDP Europe):**

2021/07/31 23:00:26 INFO openvpn: retrying in 15s,
2021/07/31 23:00:26 ERROR openvpn: no server found: for protocol udp; region italy,
2021/07/31 23:00:26 INFO shadowsocks: listening TCP on :8388,
2021/07/31 23:00:32 INFO healthcheck: program has been unhealthy for 6s: restarting OpenVPN,
2021/07/31 23:00:26 INFO shadowsocks: listening UDP on :8388

**(and below  logs are generated if into the env section i insert udp protocol, CyberGhost group and the server's hostname as well, i mean, as told before, 87-1-it.cg-dialup.net):**

2021/07/31 23:16:57 ERROR cannot read Openvpn settings: environment variable SERVER_HOSTNAME: at least one value is not within the accepted values: invalid values found: value "87-1-it.cg-dialup.net" at position 1; possible values are: 87-1-ad.cg-dialup.net, 87-1-ae.cg-dialup.net, 87-1-al.cg-dialup.net, 87-1-am.cg-dialup.net, 87-1-ba.cg-dialup.net, 87-1-be.cg-dialup.net, 87-1-bg.cg-dialup.net, 87-1-by.cg-dialup.net, 87-1-ch.cg-dialup.net, 87-1-cz.cg-dialup.net, 87-1-de.cg-dialup.net, 87-1-dz.cg-dialup.net, 87-1-ee.cg-dialup.net, 87-1-eg.cg-dialup.net, 87-1-es.cg-dialup.net, 87-1-fi.cg-dialup.net, 87-1-fr.cg-dialup.net, 87-1-gb.cg-dialup.net, 87-1-ge.cg-dialup.net, 87-1-gl.cg-dialup.net, 87-1-gr.cg-dialup.net, 87-1-hr.cg-dialup.net, 87-1-ie.cg-dialup.net, 87-1-il.cg-dialup.net, 87-1-in.cg-dialup.net, 87-1-is.cg-dialup.net, 87-1-li.cg-dialup.net, 87-1-lk.cg-dialup.net, 87-1-lt.cg-dialup.net, 87-1-lu.cg-dialup.net, 87-1-lv.cg-dialup.net, 87-1-ma.cg-dialup.net, 87-1-mc.cg-dialup.net, 87-1-md.cg-dialup.net, 87-1-me.cg-dialup.net, 87-1-mk.cg-dialup.net, 87-1-mt.cg-dialup.net, 87-1-no.cg-dialup.net, 87-1-pl.cg-dialup.net, 87-1-pt.cg-dialup.net, 87-1-qa.cg-dialup.net, 87-1-rs.cg-dialup.net, 87-1-ru.cg-dialup.net, 87-1-sa.cg-dialup.net, 87-1-se.cg-dialup.net, 87-1-si.cg-dialup.net, 87-1-sk.cg-dialup.net, 87-1-tr.cg-dialup.net, 87-1-za.cg-dialup.net, 93-1-ar.cg-dialup.net, 93-1-br.cg-dialup.net, 93-1-bs.cg-dialup.net, 93-1-ca.cg-dialup.net, 93-1-cl.cg-dialup.net, 93-1-co.cg-dialup.net, 93-1-mx.cg-dialup.net, 93-1-us.cg-dialup.net, 93-1-ve.cg-dialup.net, 94-1-ar.cg-dialup.net, 94-1-br.cg-dialup.net, 94-1-bs.cg-dialup.net, 94-1-ca.cg-dialup.net, 94-1-cl.cg-dialup.net, 94-1-co.cg-dialup.net, 94-1-cr.cg-dialup.net, 94-1-mx.cg-dialup.net, 94-1-us.cg-dialup.net, 94-1-ve.cg-dialup.net, 95-1-au.cg-dialup.net, 95-1-bd.cg-dialup.net, 95-1-hk.cg-dialup.net, 95-1-ir.cg-dialup.net, 95-1-jp.cg-dialup.net, 95-1-ke.cg-dialup.net, 95-1-kh.cg-dialup.net, 95-1-kr.cg-dialup.net, 95-1-mn.cg-dialup.net, 95-1-my.cg-dialup.net, 95-1-nz.cg-dialup.net, 95-1-ph.cg-dialup.net, 95-1-pk.cg-dialup.net, 95-1-sg.cg-dialup.net, 95-1-tw.cg-dialup.net, 95-1-vn.cg-dialup.net, 95-1-za.cg-dialup.net, 96-1-au.cg-dialup.net, 96-1-bd.cg-dialup.net, 96-1-cn.cg-dialup.net, 96-1-hk.cg-dialup.net, 96-1-id.cg-dialup.net, 96-1-jp.cg-dialup.net, 96-1-ke.cg-dialup.net, 96-1-kh.cg-dialup.net, 96-1-mn.cg-dialup.net, 96-1-mo.cg-dialup.net, 96-1-my.cg-dialup.net, 96-1-nz.cg-dialup.net, 96-1-ph.cg-dialup.net, 96-1-pk.cg-dialup.net, 96-1-sg.cg-dialup.net, 96-1-th.cg-dialup.net, 96-1-tw.cg-dialup.net, 96-1-vn.cg-dialup.net, 96-1-za.cg-dialup.net, 97-1-ad.cg-dialup.net, 97-1-ae.cg-dialup.net, 97-1-al.cg-dialup.net, 97-1-am.cg-dialup.net, 97-1-at.cg-dialup.net, 97-1-ba.cg-dialup.net, 97-1-be.cg-dialup.net, 97-1-bg.cg-dialup.net, 97-1-by.cg-dialup.net, 97-1-ch.cg-dialup.net, 97-1-cz.cg-dialup.net, 97-1-de.cg-dialup.net, 97-1-dk.cg-dialup.net, 97-1-dz.cg-dialup.net, 97-1-eg.cg-dialup.net, 97-1-es.cg-dialup.net, 97-1-fi.cg-dialup.net, 97-1-fr.cg-dialup.net, 97-1-gb.cg-dialup.net, 97-1-gl.cg-dialup.net, 97-1-gr.cg-dialup.net, 97-1-hu.cg-dialup.net, 97-1-im.cg-dialup.net, 97-1-in.cg-dialup.net, 97-1-is.cg-dialup.net, 97-1-it.cg-dialup.net, 97-1-kz.cg-dialup.net, 97-1-li.cg-dialup.net, 97-1-lk.cg-dialup.net, 97-1-lt.cg-dialup.net, 97-1-lu.cg-dialup.net, 97-1-lv.cg-dialup.net, 97-1-ma.cg-dialup.net, 97-1-mc.cg-dialup.net, 97-1-md.cg-dialup.net, 97-1-me.cg-dialup.net, 97-1-mk.cg-dialup.net, 97-1-ng.cg-dialup.net, 97-1-nl.cg-dialup.net, 97-1-no.cg-dialup.net, 97-1-pa.cg-dialup.net, 97-1-pt.cg-dialup.net, 97-1-qa.cg-dialup.net, 97-1-rs.cg-dialup.net, 97-1-ru.cg-dialup.net, 97-1-sa.cg-dialup.net, 97-1-se.cg-dialup.net, 97-1-si.cg-dialup.net, 97-1-sk.cg-dialup.net, 97-1-tr.cg-dialup.net, 97-1-ua.cg-dialup.net, 97-1-za.cg-dialup.net,
2021/07/31 23:16:57 INFO Shutdown successful

**Comment by VMax2** [comment]
### **The only strange log messages that i find when i use tcp protocol are:**

2021/07/31 23:30:29 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.145:36620: i/o timeout

2021/07/31 23:30:31 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.145:36638: i/o timeout

2021/07/31 23:30:34 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.145:36644: i/o timeout

2021/07/31 23:30:35 DEBUG shadowsocks: TCP relay error: read tcp 127.0.0.1:37296->127.0.0.1:53: i/o timeout

2021/07/31 23:30:35 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:56442->18.198.241.208:5222: i/o timeout

2021/07/31 23:30:35 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:41488->161.117.98.205:443: i/o timeout

2021/07/31 23:30:35 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:39742->142.250.180.138:443: i/o timeout

2021/07/31 23:30:35 DEBUG shadowsocks: TCP relay error: read tcp 127.0.0.1:37302->127.0.0.1:53: i/o timeout

2021/07/31 23:30:35 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:40520->142.250.141.188:5228: i/o timeout

2021/07/31 23:30:38 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.254:44966: i/o timeout

2021/07/31 23:30:40 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.254:44976: i/o timeout

2021/07/31 23:30:40 DEBUG shadowsocks: TCP relay error: read tcp 127.0.0.1:37336->127.0.0.1:53: i/o timeout

2021/07/31 23:30:40 DEBUG shadowsocks: TCP relay error: read tcp 127.0.0.1:37332->127.0.0.1:53: i/o timeout

2021/07/31 23:31:09 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.254:45000: i/o timeout

2021/07/31 23:31:48 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.254:44982: i/o timeout

2021/07/31 23:33:50 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.254:45008: i/o timeout

2021/07/31 23:34:27 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.254:45010: i/o timeout

2021/07/31 23:35:19 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:53456->142.250.180.170:443: i/o timeout

2021/07/31 23:41:02 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.254:45012: i/o timeout

2021/07/31 23:49:29 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.254:45014: i/o timeout

2021/07/31 23:52:59 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.254:45020: i/o timeout

2021/07/31 23:53:29 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:33336->172.217.218.188:5228: i/o timeout

2021/07/31 23:53:30 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.254:45022: i/o timeout

2021/07/31 23:54:42 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.254:45030: i/o timeout

2021/07/31 23:55:04 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:55436->142.250.180.131:443: i/o timeout

2021/07/31 23:55:04 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:55438->142.250.180.131:443: i/o timeout

2021/07/31 23:56:50 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.254:45044: i/o timeout

2021/07/31 23:57:50 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->192.168.1.254:45058: i/o timeout

2021/07/31 23:58:16 DEBUG shadowsocks: TCP relay error: read tcp 127.0.0.1:39158->127.0.0.1:53: i/o timeout

2021/07/31 23:58:16 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:41500->142.250.180.138:443: i/o timeout

2021/07/31 23:58:16 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:37412->18.159.185.249:5222: i/o timeout

2021/07/31 23:58:16 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:34872->172.217.218.188:5228: i/o timeout

2021/07/31 23:58:42 DEBUG shadowsocks: TCP relay error: read tcp 127.0.0.1:39194->127.0.0.1:53: i/o timeout

2021/07/31 23:58:42 DEBUG shadowsocks: TCP relay error: read tcp 127.0.0.1:39192->127.0.0.1:53: i/o timeout

2021/07/31 23:58:42 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:56806->216.58.206.67:443: i/o timeout

2021/07/31 23:58:42 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:38308->18.196.247.70:5222: i/o timeout

2021/07/31 23:58:42 DEBUG shadowsocks: TCP relay error: read tcp 10.47.5.26:35162->172.217.218.188:5228: i/o timeout



### **192.168.1.254 is my router lan ip, 192.168.1.145 is my device's ip inside the lan (my cellphone)**

**Comment by qdm12** [comment]
> following logs are generated if i don't specify the server hostname but into the env section i specify only the protocol udp and the CyberGhost Group premium UDP Europe

Are you sure you are not specifying the region as `italy` anywhere? It seems like it to me 🤔 If so, then it's expected since there is no UDP italy in the gluetun program (in here: https://github.com/qdm12/gluetun/blob/master/internal/constants/servers.json).

> below logs are generated if into the env section i insert udp protocol, CyberGhost group and the server's hostname as well, i mean, as told before, 87-1-it.cg-dialup.net:

This is expected since the program did not find `87-1-it.cg-dialup.net` last time I updated it (because it did not DNS resolve to anything). Probably a problem on Cyberghost's side when I did the update.

Now `87-1-it.cg-dialup.net` seems to be up, so I ran the updater for that servers.json file and it did find it. I pushed it as commit f339c882d7a31939809287abe73858980cc65ffc it should be in the latest docker image shortly.

> The only strange log messages that i find when i use tcp protocol are:

That can happen especially with long distance tunneling I guess. Try with UDP see if it produces similar logs? As I recall I do get similar timeout errors and that's ok.

**Comment by VMax2** [comment]
> Are you sure you are not specifying the region as italy anywhere?

Yes i did it, so, if i use udp protocol i have to leave blank the region field?

If so i will wait for the latest image and will try to follow your directives, also i will let you know about shadowsocks logs under udp protocol :)

Thank you again, love your container :)

**Comment by qdm12** [comment]
> Yes i did it, so, if i use udp protocol i have to leave blank the region field?

No but in this case there was no Italy region for the UDP group.

Groups, hostnames, regions etc act as filters in the order from larger subset to narrower:

- group
- region
- hostname

Although a region can occur in multiple groups.

Anyway now Italy should be back for both tcp and udp if you re-pull the image.

**Comment by VMax2** [comment]
Yes right, now everything has came working back as it should, just in the log file i still see the error about i/o timeout with shadowsocks even if i'm using UDP protocol as you suggested i.e.

> _2021/08/01 12:01:42 DEBUG shadowsocks: TCP relay error: read tcp 172.17.0.3:8388->80.104.100.105:59522: i/o timeout_

and this new error too

> _2021/08/01 12:00:19 ERROR shadowsocks: cannot connect to target address 0.0.0.0:53: dial tcp 0.0.0.0:53: connect: connection refused_


in anycase all seems to be working regulary, thank you so much!!! :)
